export const MODEL_ANSWERS: Record<string, string> = {

  // ─── FASE 1 ───────────────────────────────────────────────────────────────

  "1-1-1":
    "Abrí TradingView y busqué BTCUSD en gráfico diario. Identifiqué una zona de compra (LONG) el 15 de marzo, cuando el precio rebotó desde el soporte de 40.000$ con una vela martillo de gran volumen, señalando rechazo de los vendedores. Identifiqué una zona de venta (SHORT) el 28 de marzo, cuando el precio alcanzó la resistencia de 47.500$ con una estrella fugaz y el RSI en sobrecompra (>70). Anoté ambos momentos con capturas de pantalla, indicando el precio de entrada, el nivel de soporte/resistencia que los justificaba y el movimiento posterior que confirmó la lógica.",

  "1-2-1":
    "Configuré TradingView con tipo de gráfico de velas japonesas, añadí la EMA 21 en color azul y la EMA 50 en naranja desde el menú de indicadores, y el RSI de 14 periodos en el panel inferior. Guardé el layout como 'Setup Principal' para no tener que rehacerlo cada sesión. Practiqué cambiar entre temporalidades D1, H4 y H1 usando los accesos directos del teclado. Dibujé dos líneas horizontales: una en 1,0850 (resistencia reciente del EUR/USD) y otra en 1,0720 (soporte estructural de la semana anterior), marcando niveles donde el precio había reaccionado al menos dos veces.",

  "1-2-2":
    "Investigué IC Markets (regulado por ASIC y CySEC, spread EUR/USD de 0,1 pips en cuenta Raw, depósito mínimo de 200$, plataformas MT4/MT5 y cTrader), Pepperstone (regulado por FCA y ASIC, spread 0,0 pips + comisión 3,5$/lote en Razor, depósito mínimo de 200$) y XM (regulado por CySEC y ASIC, spread de 0,6 pips en cuenta Ultra Low, depósito mínimo de 5$). Elegí IC Markets por su regulación más sólida (ASIC), spreads muy bajos y la disponibilidad de MT5, que es la plataforma más moderna. Abrí una cuenta DEMO con 10.000$ de capital simulado para comenzar a practicar sin riesgo.",

  "1-3-1":
    "En EUR/USD H4 identifiqué tres Doji en zonas de resistencia (confirmando indecisión antes de caída), dos Martillos en soportes clave de 1,0720 y 1,0680 (ambos precedieron subidas de entre 80 y 120 pips), y dos Estrellas Fugaz en la resistencia de 1,0920 (ambas preceden correcciones). Encontré además un patrón Envolvente bajista en 1,0870 que marcó el inicio de una caída de 150 pips. Anoté que los patrones en zonas clave (soporte o resistencia) tuvieron un seguimiento correcto en el 80% de los casos, mientras que los patrones aislados sin nivel relevante resultaron señales falsas.",

  "1-3-2":
    "Identifiqué dos patrones Morning Star en el EUR/USD H4: el primero en el soporte de 1,0680 precedió una subida de 200 pips en tres días; el segundo en 1,0740 dio inicio a un impulso de 140 pips. Marqué dos Inside Bars en una zona de congestión entre 1,0820 y 1,0850; en ambos casos la ruptura de la vela madre fue explosiva (80-90 pips en dos horas). Localicé un Three White Soldiers que arrancó desde el soporte de 1,0700 con volumen creciente en cada vela, confirmando el dominio comprador. En cada caso anoté que el patrón solo ofreció señal de alta fiabilidad cuando coincidía con un nivel técnico relevante.",

  // ─── FASE 2 ───────────────────────────────────────────────────────────────

  "2-1-1":
    "En EUR/USD diario identifiqué las tres resistencias principales de los últimos tres meses (1,0950, 1,1050 y 1,1120) y las tres zonas de soporte (1,0720, 1,0640 y 1,0580), dibujando cada una con un rectángulo de 15-20 pips de grosor para reflejar la zona real y no una línea exacta. La zona de 1,0950 presentó tres toques (dos rechazos y luego rotura) y un cambio de polaridad claro: tras la ruptura el precio retrocedió y la zona funcionó como soporte. Identifiqué un fakeout reciente en el soporte de 1,0720: el precio perforó 12 pips por debajo, activó stops y regresó con fuerza, confirmando que el nivel seguía válido. El número redondo 1,1000 coincidió con la resistencia más fuerte del período.",

  "2-1-2":
    "En EUR/USD H4 de las dos últimas semanas identifiqué la estructura: HH en 1,0960 → HL en 1,0870 → HH en 1,1020 → HL en 1,0910, confirmando tendencia alcista. Marqué cada BOS con una línea horizontal verde (ruptura del último máximo relevante) y detecté un CHoCH bajista reciente cuando el precio rompió el HL de 1,0870 hacia abajo, marcado con línea roja. Determiné que el mercado se encontraba en la fase de Distribución de Wyckoff: el precio había hecho un Upthrust (UT) sobre la resistencia con poco volumen y luego formó un Sign of Weakness. Mi justificación se basa en el volumen decreciente en los impulsos alcistas y las mechas largas superiores en los últimos máximos.",

  "2-1-3":
    "En GBP/USD H4 de las últimas tres semanas identifiqué un canal ascendente conectando tres mínimos ascendentes (HL) en la línea de soporte y dos máximos (HH) en la línea de resistencia del canal. El ancho del canal medí 180 pips. Con el precio tocando la línea inferior del canal con una vela pin bar alcista, planeé un trade LONG: entrada en 1,2720 al cierre de la vela de confirmación, stop loss de 25 pips debajo del mínimo de la mecha (1,2695), take profit en la línea superior del canal a 1,2900 (180 pips de objetivo). El ratio R:R resultante es de 1:7,2, muy por encima del mínimo de 1:2 requerido.",

  "2-2-1":
    "En EUR/USD diario añadí la EMA 21 (azul), EMA 50 (naranja) y SMA 200 (roja). El precio se encontraba por encima de las tres medias, confirmando sesgo alcista de largo plazo. Identifiqué un Golden Cross reciente (EMA 21 cruzó por encima de la EMA 50 hace seis semanas), que fue seguido por un rally de 350 pips. Encontré tres ejemplos donde el precio rebotó en la EMA 50: dos en tendencia alcista (rebotes de 120 y 180 pips respectivamente) y uno en la SMA 200 (rebote de 240 pips desde zona de soporte mayor). Al añadir el ribbon de EMAs (9, 13, 21, 34, 55), las medias estaban expandidas y ordenadas de forma alcista, confirmando tendencia fuerte sin señal de debilitamiento.",

  "2-2-2":
    "En BTC/USD H4 añadí RSI(14) y MACD(12,26,9). Identifiqué una divergencia regular bajista clara: el precio marcó un HH en 47.500$, pero el RSI marcó un máximo más bajo (65 vs 72 en el pico anterior), señalando debilidad compradora que precedió una caída de 8.000$. Localicé un cruce MACD alcista cuando la línea MACD cruzó por encima de la señal desde -800 en el histograma, dando inicio a un movimiento de 15.000 pips al alza. Detecté un momento donde el histograma MACD empezó a disminuir (de +650 a +380) cuatro velas antes de que el precio girara a la baja, sirviendo como alerta temprana. Confirmé que las divergencias coincidieron en el 100% de los casos con niveles horizontales de soporte o resistencia.",

  "2-2-3":
    "En NAS100 H1 añadí Volume Profile (Visible Range) y OBV. Identifiqué el POC en 17.840 puntos (nivel con mayor volumen negociado, marqué con línea horizontal amarilla), el VAH en 17.920 y el VAL en 17.760. Detecté dos LVN (zonas de poco volumen) entre 17.760-17.790 y entre 17.850-17.860, donde el precio viajó muy rápido en ambas direcciones sin consolidar. El OBV mostró divergencia bajista respecto al precio en el último impulso: el precio hizo HH pero el OBV no lo confirmó, sugiriendo distribución. En las cinco velas más recientes, las velas alcistas tenían volumen 40% superior al promedio, confirmando presión compradora activa.",

  "2-3-1":
    "En BTC/USD H4 identifiqué el último impulso alcista claro desde 38.500$ hasta 47.200$ (8.700 puntos). Dibujé Fibonacci de mínimo a máximo y localicé: 38,2% en 44.880$, 50% en 42.850$, 61,8% en 40.825$ y 78,6% en 40.362$. El nivel del 61,8% coincidió con un soporte horizontal fuerte (zona de congestión previa durante dos semanas) y la EMA 50 pasaba exactamente a 40.780$, creando triple confluencia. Planifiqué el trade: entrada en 40.825$ (zona OTE entre 61,8% y 78,6%), stop loss en 39.900$ (debajo del 100%), take profit en la extensión 161,8% a 51.580$. El ratio R:R resultante es de 1:11,7; incluso con un TP conservador en 161,8% se obtiene R:R de 1:5,8.",

  "2-3-2":
    "En EUR/USD H4 identifiqué un doble techo en 1,1050 con neckline en 1,0910, proyectando caída de 140 pips hasta 1,0770. En GBP/USD diario encontré un triángulo simétrico de seis semanas entre dos líneas convergentes; calculé el target proyectado en 180 pips desde el punto de ruptura. En BTC/USD H4 marqué una bull flag: asta de 6.000 pips, consolidación bajista de 45 grados con cuatro toques en el canal; el target es la proyección del asta desde el punto de ruptura de la bandera. En NAS100 diario localicé una cuña ascendente como patrón bajista, con líneas convergentes y volumen decreciente en cada swing alcista, confirmando agotamiento comprador.",

  "2-3-3":
    "Análisis multi-timeframe de EUR/USD: en Diario confirmé tendencia bajista con estructura LH/LL; el sesgo es vendedor. En H1 dibujé Fibonacci del último impulso bajista y la zona de interés con confluencia quedó entre el 61,8% (1,0885) y la EMA 21 (1,0890), con un OB bajista sin mitigar a 1,0892. En M15 el precio llegó a la zona con un CHoCH bajista claro (ruptura de un HL menor), lo que activó el trigger de entrada. Documenté: captura D1 con estructura, captura H1 con Fibonacci y zonas marcadas, captura M15 con el trigger, entrada en 1,0890, SL en 1,0918 (por encima del OB), TP en 1,0780 (siguiente soporte D1). Ratio R:R: 1:3,9.",

  "2-4-1":
    "Revisé Forex Factory y encontré tres noticias de alto impacto para USD esta semana: IPC (martes 08:30 EST, expectativa +0,3%), NFP (viernes 08:30 EST, expectativa 185.000 empleos) y declaraciones de la Fed (miércoles 14:00 EST). El martes tras el IPC, EUR/USD subió 80 pips en los primeros 15 minutos porque el dato salió por debajo de lo esperado (+0,2%), debilitando al dólar. El miércoles las declaraciones de Powell fueron hawkish y el EUR/USD cayó 120 pips en 30 minutos. El viernes el NFP superó expectativas (210.000 vs 185.000) y EUR/USD cayó 95 pips en los primeros 5 minutos, con un spread que se amplió de 1,2 a 8 pips momentáneamente.",

  "2-5-1":
    "En OptionsProfit Calculator con Apple (AAPL) a 185$: compré un Call con strike 194,25$ (5% superior), vencimiento a 30 días, prima de 2,40$ por acción (240$ por contrato), Delta 0,32 y Theta -0,08 (pierde 8 centavos al día). Compré un Put con strike 175,75$ (5% inferior), misma expiración, prima de 3,10$ (310$ por contrato), Delta -0,38 y Theta -0,09. La prima del Put fue 29% más cara porque el mercado tiene mayor demanda de protección bajista (skew). El break-even del Call se calculó en 194,25$ + 2,40$ = 196,65$, lo que significa que Apple debe subir al menos un 6,3% desde el precio actual en 30 días para que el Call sea rentable tras pagar la prima.",

  "2-5-2":
    "En Yahoo Finance analicé tres acciones del S&P 500 de diferentes sectores: Apple (tecnología), Johnson & Johnson (salud) y Chevron (energía). Apple con P/E de 28 (sector promedio 32, relativamente barato); último trimestre EPS de 2,18$ vs estimado 2,09$ (+4,3%, supera expectativas); revenue creciendo 6% YoY. J&J con P/E de 24 (sector promedio 22, ligeramente caro); EPS en línea con estimados; revenue plano. Chevron con P/E de 14 (sector promedio 12); EPS superó en un 8%; revenue cayendo 3% por precio del petróleo. En TradingView, Apple en soporte técnico clave (EMA 200 + soporte horizontal en 172$), configurando el setup técnico más atractivo de los tres.",

  "2-5-3":
    "Desde ForexFactory anoté las fechas del próximo NFP (primer viernes del mes siguiente, consensus 178.000), CPI (segundo martes, consensus +0,3%) y FOMC (tercer miércoles, mercado descuenta pausa). Durante el NFP, EUR/USD se movió 145 pips en los primeros 5 minutos (dato salió en 220.000, muy por encima); el spread se amplió de 0,9 pips a 12 pips durante el primer minuto y se normalizó a 1,5 pips a los 8 minutos. A los 20 minutos hubo un pullback tradeable del 38,2% del movimiento inicial (45 pips de corrección) donde habría entrado SHORT con SL de 20 pips sobre el HH post-noticia. Marqué en el gráfico M15 el punto de entrada óptimo usando el protocolo post-noticia.",

  "2-5-4":
    "En el S&P 500 diario (SPY) identifiqué 10 gaps en los últimos 3 meses: 4 Common Gaps (todos se llenaron en menos de 3 días), 2 Breakaway Gaps (ninguno se llenó, confirmando inicio de tendencia), 3 Runaway Gaps en medio de tendencia alcista (solo uno se llenó, parcialmente, tras una semana), y 1 Exhaustion Gap al final de un rally de 6 semanas (se llenó en dos días). En EUR/USD H1 localicé el último weekend gap de 18 pips del domingo de apertura; se llenó completamente en las primeras 4 horas del lunes, siguiendo el patrón típico de los gap fill en Forex. El tamaño promedio de los gaps fue de 0,4% y el tiempo medio de relleno de los Common Gaps fue de 1,5 días.",

  "2-5-5":
    "Creé el layout con 6 gráficos en temporalidad diaria. El DXY mostró tendencia bajista (por debajo de la SMA 200, estructura LH/LL). Los yields US10Y bajando de 4,8% a 4,3% en el último mes, reduciendo el atractivo del USD. El VIX en zona de complacencia (15,2), indicando mercados calmados y apetito por riesgo. El petróleo WTI estable entre 78-82$. El S&P 500 en máximos históricos confirmando Risk-On. El Oro con tendencia alcista (+8% en el último mes), también confirmando debilidad del dólar. Mi lectura intermarket: contexto Risk-On fuerte con dólar débil, favorece LONG en EUR/USD, GBP/USD y compras en índices; SHORT en USD/JPY.",

  // ─── FASE 3 ───────────────────────────────────────────────────────────────

  "3-1-1":
    "Creé una hoja de cálculo en Excel y simulé 50 operaciones con riesgo del 1% (100$ por trade en cuenta de 10.000$), ratio 1:2 y 45% de acierto. Resultado: 22 ganancias × 200$ = 4.400$ y 28 pérdidas × 100$ = 2.800$; beneficio neto +1.600$ (16%), drawdown máximo del 7,3%. Con riesgo del 5% (500$ por trade) el resultado fue: mismas probabilidades pero beneficio neto de +8.000$ en el escenario favorable pero drawdown máximo del 34,5%, con varias rachas que llevaron la cuenta por debajo del 50% inicial. Conclusión clara: el riesgo del 1% produce resultados positivos con un drawdown psicológicamente manejable, mientras el 5% puede generar el mismo rendimiento pero con riesgo de ruina en rachas perdedoras normales.",

  "3-1-2":
    "Con capital simulado de 10.000$ y riesgo del 1% (100$): para EUR/USD con SL de 25 pips, el tamaño es 100$ / (25 × 10$) = 0,40 lotes; con SL de 75 pips, es 100$ / (75 × 10$) = 0,13 lotes; para GBP/USD con SL de 50 pips, es 100$ / (50 × 10$) = 0,20 lotes. En TradingView identifiqué tres setups en EUR/USD H4: un rebote en soporte con SL de 30 pips (0,33 lotes), un OB bajista en resistencia con SL de 20 pips (0,50 lotes) y una bandera alcista con SL de 45 pips (0,22 lotes). En todos los casos el tamaño de posición se ajustó para que el riesgo en dólares fuera exactamente 100$ independientemente de la distancia al stop.",

  "3-1-3":
    "Copié la plantilla del plan de trading y completé cada sección: mercado (EUR/USD y GBP/USD, sesión London-NY), estrategia (Price Action + SMC, busco OB con FVG y confluencia Fibonacci), riesgo por operación (1%, máximo 2% diario), ratio mínimo (1:2, objetivo 1:3), horario (08:00-12:00 UTC y 13:00-17:00 UTC), reglas de drawdown (parar si pierdo 2 seguidas o llego al 2% diario), revisión semanal cada domingo. Imprimí el plan en A4 y lo pegué en el lateral del monitor. Apliqué la pregunta filtro ('¿esto cumple con mi plan?') en los primeros cinco trades de prueba: rechacé dos setups que no cumplían criterios de confluencia mínimos.",

  "3-2-1":
    "Durante una semana en cuenta demo llevé el diario emocional: lunes antes del trade sentí urgencia (impaciencia), el trade perdió porque entré sin confirmación completa; miércoles sentí euforia tras dos ganancias seguidas (codicia), el tercer trade fue sobredimensionado y perdí el doble; jueves sentí miedo antes de un setup muy claro, no entré y el precio fue sin mí. Al final de la semana identifiqué que mi mayor enemigo es la CODICIA: cuando voy ganando, aumento el tamaño o muevo el TP, destruyendo el R:R planificado. Mi segundo enemigo es el MIEDO: me paraliza ante setups válidos si he tenido pérdidas recientes.",

  "3-2-2":
    "Creé el diario de trading en Google Sheets con las columnas: Fecha, Par, Dirección (L/S), Entrada, SL, TP, R:R, Lotes, Riesgo$, Resultado$, Seguí plan (S/N), Emoción pre-trade (1-5), Nota emocional. Registré las primeras 20 operaciones en demo durante dos semanas. Al final calculé: winrate del 45%, R:R promedio de 2,1:1, esperanza matemática positiva (+0,45R por trade). Encontré un patrón claro: los trades abiertos entre las 08:00-10:00 UTC (sesión londinense temprana) tuvieron winrate del 30%, mientras los abiertos entre las 13:00-15:00 UTC (solapamiento) tuvieron winrate del 60%. Eliminé las entradas fuera del solapamiento.",

  "3-2-3":
    "Durante 30 días, cada mañana leí las siete frases de reprogramación en voz alta y luego evalué mi estado en cuatro dimensiones del 1 al 5. Los días en que la confianza o la calma estaban por debajo de 3 (ocurrió ocho veces el primer mes) no operé. Comparando las dos primeras semanas vs las dos últimas: el winrate mejoró del 38% al 52%, el número de trades por impulsividad (emoción alta) cayó de 6 a 1, y los días con pérdidas mayores al 1,5% de la cuenta se redujeron de 4 a 0. La correlación entre estado emocional bajo (<3 en calma) y resultado negativo fue del 87%, confirmando que el check emocional es un filtro rentable.",

  // ─── FASE 4 ───────────────────────────────────────────────────────────────

  "4-1-1":
    "En EUR/USD M15 de los últimos tres días marqué 11 equal highs y 9 equal lows. De los 11 equal highs, 8 fueron barridos (el precio los superó brevemente y revirtió) antes de un movimiento bajista de al menos 30 pips, y solo 3 fueron respetados. De los 9 equal lows, 7 fueron barridos antes de un movimiento alcista significativo. Repetí el ejercicio en GBP/USD y USD/JPY con resultados similares: el 70-75% de los equal highs/lows fueron barridos antes del movimiento real. Conclusión: los equal highs y equal lows son imanes de liquidez que el precio casi siempre visita antes de moverse en la dirección opuesta; operar después del sweep con confirmación de BOS genera entradas de alta probabilidad.",

  "4-1-2":
    "En GBP/USD H1 identifiqué cinco BOS de las últimas dos semanas y para cada uno marqué el Order Block que lo causó. BOS nº1 (alcista en 1,2680): el OB era la última vela bajista antes del impulso, zona 1,2640-1,2658; cuando el precio retrocedió, rebotó exactamente desde esa zona con pin bar. BOS nº2 (bajista): OB en 1,2820-1,2835, precio retrocedió, formó una envolvente bajista en la zona y cayó 90 pips. Refiné los OBs nº3 y nº4 bajando a M15: el OB de H1 tenía 20 pips de ancho pero el OB refinado en M15 quedó en 8 pips, mejorando el R:R de 1:2,5 a 1:4. Los OBs frescos (primer toque) funcionaron en el 80% de los casos; los ya mitigados (segundo toque) solo en el 40%.",

  "4-2-1":
    "Durante cinco días consecutivos marqué el rango asiático de EUR/USD M15 cada mañana (entre las 00:00 y las 08:00 UTC). Resultados: lunes, rango 1,0820-1,0848 (28 pips); London abrió y barrió el low a 1,0814, luego BOS alcista y distribución hasta 1,0890 (+76 pips desde el sweep). Martes, London barrió el high, reversa bajista de 95 pips. Miércoles, ruptura directa sin manipulación (Day Trend, no AMD). Jueves y viernes repitieron el patrón AMD. Resultado: 4 de 5 días mostraron el patrón AMD (80%), confirmando que el Power of 3 es una herramienta de alta fiabilidad durante sesiones normales sin noticias de alto impacto.",

  "4-2-2":
    "En EUR/USD M15 identifiqué los tres últimos FVGs: un BISI (Buy Side Imbalance Sell Side Inefficiency) alcista entre 1,0842 y 1,0851 (precio lo llenó hasta el 50% antes de continuar), un SIBI bajista entre 1,0889 y 1,0898 (precio llegó exactamente hasta el CE en 1,0893 y revirtió) y un BISI en 1,0817-1,0825. Dibujé Fibonacci del último swing y la zona Premium/Discount: compras en Discount (<1,0835), ventas en Premium (>1,0865). Encontré un trade histórico con cuatro confluencias: Killzone London (09:15 UTC) + liquidity sweep de equal lows + OB bajista + zona Premium + FVG SIBI. La entrada en el OB con TP en el siguiente soporte D1 habría dado R:R de 1:6,2.",

  "4-3-1":
    "En GBP/USD H1 con gráfico limpio identifiqué tres zonas de demanda (patrones DBR): primera en 1,2620-1,2635 (caída rápida de 80 pips, consolidación de cuatro velas y rally de 180 pips), segunda en 1,2710-1,2725 y tercera en 1,2680-1,2692. Marqué tres zonas de supply (patrones RBD): en 1,2890-1,2905, 1,2860-1,2872 y 1,2840-1,2850. Las tres zonas de demanda eran frescas (primer toque), lo que aumenta la probabilidad de reacción. Al comparar con los Order Blocks de la lección anterior, las zonas de demanda DBR coincidían con los OBs alcistas en el 90% de los casos, confirmando que ambos conceptos identifican la misma actividad institucional.",

  "4-3-2":
    "En BTC/USD Diario identifiqué el ciclo de acumulación de 2022-2023: PS (Preliminary Support) en 27.000$, SC (Selling Climax) en 15.500$ con volumen pico, AR (Automatic Rally) hasta 21.000$, ST (Secondary Test) en 16.800$ con volumen menor. El Spring apareció en noviembre de 2022 a 15.500$, perforando el SC por 200$ antes de rebotar con fuerza. SOS (Sign of Strength) en enero de 2023 con ruptura de la resistencia del rango a 23.000$ y LPS (Last Point of Support) en retroceso a 21.500$. Traduje a terminología SMC: el Spring fue un liquidity sweep de los lows; el SOS fue un BOS alcista masivo; el LPS fue la última zona de OB alcista antes del markup de 2023 a 73.000$.",

  "4-3-3":
    "Creé el sistema completo: par EUR/USD, timeframe H4 para análisis + H1 para entrada, killzone London-NY. Checklist de confluencias: 1) Tendencia HTF (diario) a favor, 2) Precio en zona de OB o FVG, 3) Nivel de Fibonacci (61,8%-78,6%), 4) Killzone activa, 5) Liquidity sweep previo, 6) BOS/CHoCH en H1, 7) Vela de confirmación en LTF. Realicé backtest de 50 trades en Replay de TradingView: trades con 5+ confluencias tuvieron winrate del 68% y R:R promedio de 2,8; trades con 3-4 confluencias: winrate del 52% y R:R de 2,1; trades con menos de 3: winrate del 31%. Decisión: solo entrar con mínimo 4 confluencias; target mínimo de R:R 1:2,5.",

  "4-5-1":
    "En el gráfico de futuros ES en TradingView activé el indicador Market Profile (TPO). El POC del día anterior se encontraba en 4.958, marcado con línea horizontal amarilla. El VAH fue 4.972 y el VAL fue 4.944, definiendo el Value Area con el 70% del volumen. El Initial Balance de la sesión de hoy (primera hora) fue estrecho, de solo 12 puntos, sugiriendo un día de tendencia potencial. Identifiqué single prints en la zona 4.978-4.982 (letras aisladas sin TPOs adyacentes), representando desequilibrio. El POC de ayer (4.958) coincidía con un OB alcista en H1 entre 4.955-4.960; cuando el precio llegó a esa zona a las 10:20 EST formó una envolvente alcista y subió 28 puntos.",

  "4-5-2":
    "Observé el contrato ES en la plataforma de futuros durante 30 minutos en la apertura de NY (09:30-10:00 EST). Identifiqué un muro de 2.400 contratos en el bid a 4.960 que se mantuvo durante 8 minutos absorbiendo toda la presión vendedora (ejemplo claro de absorción alcista). Un segundo muro de 1.800 contratos en el ask a 4.975 desapareció antes de que el precio llegara (posible spoofing). En el tape localicé 5 transacciones de 200+ contratos, todas al ask (compras agresivas) en el rango 4.961-4.963, confirmando acumulación institucional. Veinte minutos después el precio superó el muro del ask y subió 18 puntos, confirmando que la absorción a 4.960 fue genuina.",

  "4-5-3":
    "Creé el tracker en Google Sheets con las columnas especificadas. Simulé tres trades simultáneos en cuenta de 10.000$: LONG EUR/USD (entrada 1,0845, SL 1,0820, TP 1,0895, riesgo 1,5% = 150$, correlación EUR/GBP +0,87), LONG GBP/JPY (entrada 190,50, SL 189,80, riesgo 1,5% = 150$) y SHORT XAU/USD (entrada 2.010, SL 2.022, riesgo 1,5% = 150$). Portfolio Heat total: 4,5% (dentro del límite del 5%). Al añadir un 4º trade hipotético SHORT GBP/USD (riesgo 1,5%), el heat sería 6%, superando el límite. En myfxbook.com/forex-market/correlation verifiqué que EUR/USD y GBP/USD tienen correlación de +0,82, confirmando que los dos longs con USD están correlacionados y cuentan como doble exposición.",

  "4-5-4":
    "En EUR/USD H4 añadí Bollinger Bands (20, 2), RSI(14) y ADX(14). Identifiqué 10 momentos donde el RSI bajó de 20 o superó 80 con ADX por debajo de 25: en 9 de los 10 casos el precio regresó a la SMA 20 en las siguientes 8-15 velas (90% de win rate). En cambio, busqué 3 momentos con RSI en extremo pero ADX mayor a 30: en los tres casos el precio continuó en la dirección de la tendencia sin regresar a la media (0% de éxito con mean reversion). Conclusión: el filtro ADX < 25 es imprescindible para aplicar mean reversion; sin él la estrategia tiene un win rate cercano al 30%. El R:R típico fue 1:1,8 (SL justo por encima del extremo, TP en la SMA 20).",

  "4-5-5":
    "En SeasonalCharts.com recopilé los patrones estacionales de EUR/USD (bullish marzo-abril, neutral mayo-agosto, bearish septiembre-octubre), S&P 500 (bullish noviembre-enero, peor mes septiembre con -0,7% promedio) y Gold (bullish enero-febrero y agosto-septiembre). Creé la hoja de cálculo con 12 filas y añadí una columna de 'eventos clave' con NFP, FOMC y vencimientos trimestrales. El mes actual muestra sesgo estacional alcista en el S&P 500 (+1,4% promedio en noviembre). Identifiqué un setup técnico: el S&P 500 retrocedió a un OB alcista en H4 con la estacionalidad favorable; documenté el trade en papel: entrada 4.435, SL 4.410 (25 puntos), TP 4.510 (75 puntos), R:R 1:3.",

  // ─── FASE 5 ───────────────────────────────────────────────────────────────

  "5-1-1":
    "Visité ftmo.com y fundednext.com y elaboré la tabla comparativa: FTMO para 100K cuesta 540€ (2 fases, Fase 1 +10% en 30 días, Fase 2 +5% en 60 días, DD diario 5%, total 10%, profit split 80% escalable al 90%). Funded Next para 100K cuesta 299-499€ según modalidad (opción 1 fase o 2 fases, plazo ilimitado, DD diario 5%, total 10%, profit split 80%). Elegiría Funded Next para un primer intento por el precio inferior (ahorro de ~200€), el plazo ilimitado (menor presión psicológica) y condiciones de drawdown idénticas. Si supero el primer challenge, escalaría a FTMO por su mayor reputación y mejor historial de pagos en la industria.",

  "5-1-2":
    "Abrí la cuenta demo con 100.000$ con las reglas exactas del challenge. Semana 1: opero exclusivamente EUR/USD en solapamiento London-NY con riesgo de 0,5% por trade. Lunes: +1,2% (2 trades ganadores con R:R promedio de 2,4). Martes: +0,0% (1 trade que llegó a TP parcial y SL en breakeven). Miércoles: -0,5% (1 pérdida, paré al alcanzar el límite diario personal). Jueves: +0,8%. Viernes: +0,3% (solo 1 trade, evité la tarde). Resultado semana 1: +1,8% con drawdown máximo diario de 0,5%, muy por debajo del límite del 5%. El diario emocional reveló que los miércoles con FOMC soy más impaciente.",

  "5-1-3":
    "Creé el Plan de Trader Fondeado: objetivo en 6 meses es tener 2 cuentas de 100K (1 FTMO + 1 Funded Next) con trade copier. Riesgo máximo: 0,5-1% por trade, parar si drawdown diario supera el 3%. Plan de retiro: retirar el 60% de ganancias quincenalmente y dejar el 40% como colchón. Presupuesto mensual para challenges: 150€ (equivalente a 1 challenge de 10K de reserva). Si pierdo la primera cuenta: 2 semanas de pausa, revisar el diario, volver a demo 10 días antes del siguiente intento. Horario diario: análisis pre-market 08:00-08:30 UTC, trading 13:00-17:00 UTC, revisión post-sesión 17:30-18:00 UTC. El documento está firmado y pegado junto al monitor.",

  "5-2-1":
    "Contacté a un asesor fiscal en mi ciudad especializado en mercados financieros. Las respuestas obtenidas: las ganancias de trading con broker extranjero tributan como rendimientos de capital mobiliario en la base del ahorro del IRPF (19-28% según tramo). Las ganancias de prop firms se consideran rendimientos de actividades económicas (casilla de autónomo) si son regulares y cuantiosas, con tipo efectivo generalmente mayor. Los documentos necesarios son: extractos anuales del broker, historial completo de operaciones, capturas de transferencias de prop firms, y justificación de que no estoy sujeto a la calificación de trader profesional según normativa MIFID. Recomendó abrir una sociedad limitada si los ingresos superan los 30.000€ anuales.",

  "5-2-2":
    "Revisé TrustPilot para las cuatro prop firms: FTMO tiene 4,7/5 con 18.000+ reseñas, quejas principales relacionadas con soporte lento y reversión de ganancias por uso de news trading. Funded Next tiene 4,5/5 con 9.000+ reseñas, quejas sobre retrasos en pagos puntuales. MyFundedFX tiene 4,2/5 con 3.500 reseñas, más quejas sobre cambios en las reglas. True Forex Funds tiene 4,4/5 con 4.200 reseñas. Elegiría FTMO para mi primer challenge de 25K por su trayectoria más larga (desde 2015), el mayor número de reseñas verificables y el historial probado de pagos consistentes, aunque su precio sea más alto.",

  "5-2-3":
    "Configuré la cuenta demo con 100.000$, máximo 0,5% de riesgo por trade, máximo 2 trades diarios y drawdown diario del 5%. Lunes: +0,8% (1 trade, esperé el setup óptimo). Martes: +0% (no encontré setup válido con 3+ confluencias, no operé). Miércoles: -0,4% (1 pérdida limpia, cerré la sesión). Jueves: +1,1% (2 trades ganadores en solapamiento). Viernes: +0,3%. Resultado de la semana: +1,8%, drawdown diario máximo 0,4%, sin violaciones de reglas. Evaluación: habría pasado la semana 1 de un challenge real. Punto de mejora: el martes habría podido forzar un trade de menor calidad; aprender a no operar es tan importante como saber entrar.",

  // ─── FASE 6 ───────────────────────────────────────────────────────────────

  "6-1-1":
    "Usé TradingView Replay en EUR/USD H1 retrocediendo 6 meses. Apliqué la estrategia de rebote en soporte/resistencia con confirmación de vela japonesa: entrada solo con pin bar o envolvente, SL debajo del soporte (o encima de resistencia), TP al siguiente nivel. Registré 35 trades en Excel: win rate del 54%, profit factor de 1,72, drawdown máximo del 8,4% y esperanza matemática de +0,88R por trade. Identifiqué que los trades en solapamiento London-NY tuvieron win rate del 63% vs 41% fuera del horario. Descubrí además que los trades en contra de la tendencia del diario tuvieron win rate del 31%, lo que me llevó a añadir el filtro de sesgo diario como regla del sistema.",

  "6-1-2":
    "Instalé Python 3.11 y ejecuté: pip install yfinance pandas numpy matplotlib. El script descargó datos de EURUSD=X de los últimos 2 años con yfinance, calculó la SMA 20 y SMA 50 con pandas rolling, y contó los cruces: la SMA 20 cruzó por encima de la SMA 50 en 8 ocasiones (señales de compra) y por debajo en 9 ocasiones (señales de venta). Imprimí los resultados con fechas y añadí una columna con el rendimiento del trade siguiente a cada señal. Usé ChatGPT para depurar un error de indexación en la condición de cruce. El script completo tiene 45 líneas de código y se ejecuta en menos de 3 segundos.",

  "6-1-3":
    "Abrí el editor de Pine Script en TradingView y copié el indicador RSI Pro con alertas. Lo añadí al gráfico EUR/USD H1. Modifiqué el período del RSI de 14 a 21 cambiando la variable `rsiLength`. Añadí una SMA de 200 períodos sobre el RSI con `sma(rsi, 200)` y la grafiqué con `plot()`. Creé una alerta con `alertcondition(ta.crossunder(rsi, 25), 'RSI cruza bajo 25', 'RSI cruzó debajo de 25 en EUR/USD H1')`. Experimenté cambiando los colores de las zonas de sobrecompra/sobreventa a gradiente rojo/verde y ajustando el umbral de sobreventa de 30 a 25 para reducir señales falsas.",

  "6-3-1":
    "Instalé Python y ejecuté pip install yfinance pandas. El script de descarga usó `yf.download('EURUSD=X', period='1y', interval='1d')` y guardé el DataFrame en un CSV con `df.to_csv('eurusd_diario.csv')`. Verifiqué que el archivo tenía las columnas Open, High, Low, Close, Volume y Adj Close con 252 filas (días de trading). El CSV incluye fechas desde hace un año hasta hoy, con datos limpios sin valores nulos. Añadí una verificación automática con `df.isnull().sum()` que confirmó cero valores faltantes.",

  "6-3-2":
    "Con scikit-learn creé un clasificador RandomForest. Preparé las features: RSI(14) y SMA 20 calculados sobre los datos diarios de EUR/USD, usando shift(1) para evitar look-ahead bias. La variable target fue 1 si el precio sube mañana, 0 si baja. Dividí los datos cronológicamente: 80% para entrenamiento (datos más antiguos) y 20% para validación (datos más recientes). El accuracy en el set de validación fue del 53%, apenas por encima del azar. Añadí más features (RSI anterior, retornos de 5 días, volatilidad) y el accuracy subió al 56%. Conclusión: el modelo tiene valor estadístico marginal como filtro adicional, no como señal principal.",

  "6-3-3":
    "Creé una cuenta en DigitalOcean y desplegué un Droplet de Ubuntu 22.04 (5$/mes). Me conecté por SSH y configuré Python 3 con pip. Subí un script Python que imprimía la hora cada minuto usando `datetime.now()` dentro de un bucle con `time.sleep(60)`. Verifiqué su ejecución por SSH durante 10 minutos. Luego creé un cron job con `crontab -e` añadiendo la línea `0 * * * * python3 /root/script.py >> /root/log.txt 2>&1` para que se ejecute cada hora. Tras 3 horas verifiqué que el log.txt tenía tres entradas con las horas correspondientes.",

  // ─── FASE 7 ───────────────────────────────────────────────────────────────

  "7-1-1":
    "Realicé el examen completo de 20 preguntas anotando respuestas en papel sin consultar las lecciones. Obtuve 17/20 (85%), superando el mínimo requerido del 80%. Las tres respuestas incorrectas fueron sobre la clasificación exacta de los ciclos de Wyckoff avanzados (Fase 2, lección 4-3-2), el cálculo específico del Z-Score en mean reversion (Fase 4, lección 4-5-4) y la diferencia entre tipos de Fibonacci extensions (lección 2-3-1). Programé una segunda sesión de estudio en 7 días enfocada en estos tres temas. Repetí el examen una semana después y obtuve 20/20.",

  "7-1-2":
    "Creé el Plan de Carrera completo: estrategia elegida (SMC + ICT, Price Action puro), par principal EUR/USD y secundario GBP/USD, timeframe H4 para análisis y H1 para entrada, riesgo 0,75% por trade. Horario: lunes a jueves de 13:00 a 17:00 UTC. Timeline 12 meses: meses 1-2 backtest y demo, meses 3-4 demo con rentabilidad positiva dos meses seguidos, meses 5-6 challenge de 10K, mes 7 primera cuenta fondeada de 50K, meses 8-12 escalar a 2 cuentas de 100K. Presupuesto: 300€ para challenges (3 intentos de 10K). Progreso documentado en diario + MyFXBook. Compromiso firmado con fecha y colocado en el escritorio.",

  "7-1-3":
    "Cronometré el examen de 10 preguntas: terminé en 14 minutos y 30 segundos (1 min 27 seg por pregunta), bien por debajo del límite de 20 minutos. Obtuve 9/10 (90%), superando el nivel profesional del 80%. La única pregunta fallada fue el escenario de correlación DXY con setup técnico opuesto, donde elegí entrar por las confluencias técnicas sin considerar el contexto macro. Score: 90% en 14,5 minutos; nivel profesional confirmado según el criterio del examen.",

  "7-1-4":
    "Escribí mi compromiso personal como trader: quiero ser trader porque busco libertad financiera y geográfica, y porque me apasiona el análisis de mercados. Estoy dispuesto a sacrificar 2 horas diarias de ocio, reducir el tiempo en redes sociales y aceptar meses de pérdidas como parte del aprendizaje. Dedicaré un mínimo de 2 horas diarias (análisis + estudio) de lunes a viernes. Firmé el documento con mi nombre y fecha de hoy. Lo imprimí y lo pegué en la pared frente a mi escritorio, visible cada vez que me siento a operar.",

  "7-2-1":
    "Imprimí la checklist y la repasé honestamente con boli verde y rojo. Verde (domino): todas las lecciones de velas, soportes/resistencias, estructura de mercado, gestión de riesgo, psicología básica, prop firms y backtesting. Rojo (necesito repasar): Ondas de Elliott (lección 4-4-1, no dominé el conteo avanzado), Market Profile (lección 4-5-1, necesito más práctica con el DOM) y los ciclos de Wyckoff en distribución (lección 4-3-2, confundo eventos ST y UT). Plan de repaso: dedicar 45 minutos a cada uno de los tres puntos rojos durante la próxima semana, hacer los ejercicios prácticos de cada lección y pasar al quiz hasta obtener 100%.",

  "7-2-2":
    "Creé cuenta en TradingView Free (guardé layout con EMA 21/50/200 y RSI 14). Descargué MetaTrader 5 y abrí cuenta demo con IC Markets (100.000$ de balance simulado). Creé cuenta en Forex Factory y configuré el calendario en zona horaria UTC+1, filtrando solo noticias de alto impacto (rojo). Registré en MyFXBook y conecté la cuenta demo de MT5 siguiendo el proceso de verificación por contraseña de solo lectura. Tomé captura de pantalla de cada plataforma configurada: TradingView con mi layout, MT5 con la cuenta demo activa, Forex Factory con el filtro horario y MyFXBook mostrando las estadísticas iniciales.",

  // ─── FASE 8 ───────────────────────────────────────────────────────────────

  "8-1-2":
    "Antes de cada sesión de la semana marqué 2 soportes y 2 resistencias en EUR/USD H4 y configuré alertas de precio en TradingView. Lunes: el precio llegó a mi resistencia de 1,0890 con envolvente bajista; entré SHORT, TP alcanzado en 1,0845 (+45 pips). Martes: el precio nunca llegó a ninguna de mis zonas; NO operé. Miércoles: llegó al soporte de 1,0820 con pin bar; entré LONG, SL activado por -20 pips. Jueves y viernes: sin llegada a zonas, NO operé. Balance de la semana: operé 3 veces (2 con llegada a zona + 1 señal) y esperé 2 días completos. Resultado: 2 veces esperé vs 1 vez perseguí (una entrada que forzé ligeramente). Win rate del 67%.",

  "8-2-1":
    "Cada mañana marqué los OBs y FVGs relevantes en H4. Día 1: identifiqué un OB bajista en 1,0892-1,0905 (puntuación 5: OB + FVG + S/R + Killzone + estructura bajista); precio llegó, entré SHORT, TP en 1,0845, resultado +47 pips (+2R). Día 2: un OB alcista con solo 2 confluencias; no entré. Día 3: setup con 4 confluencias (puntuación 4), entré, SL activado. Día 4: puntuación 6 (setup A+); +65 pips. Día 5: puntuación 3, no entré. Correlación al final de la semana: puntuación ≥4 = 2 ganadores de 2 intentos (100%), puntuación <4 = 1 perdedor descartado. Confirmé que el sistema de puntuación funciona como filtro.",

  "8-2-2":
    "Cinco días consecutivos documenté el AMD. Lunes: rango 1,0818-1,0843 (25 pips); London barrió el low en 1,0813, BOS alcista en M15, AMD completo; distribución hasta 1,0878 (+65 pips desde el sweep). Martes: rango 1,0830-1,0858; London barrió el high, AMD bajista completo, +55 pips. Miércoles: NFP day, rango asiático roto directamente hacia arriba sin sweep (no AMD, día de tendencia). Jueves: AMD completo alcista. Viernes: rango muy estrecho de 8 pips, London barrió ambos extremos (volatilidad errática, no operé). Resultado: AMD correcto en 4 de 5 días (80%). El día con noticia de alto impacto interrumpió el patrón, confirmando la regla de no operar en días de noticias rojas.",

  "8-3-1":
    "Operé dos semanas sin cambiar ninguna regla del sistema. Semana 1: +1,4% (4 trades, winrate 50%, R:R promedio 2,8). Semana 2: -0,3% (3 trades, winrate 33%, R:R 2,1); el resultado negativo se debió a dos setups válidos con 4+ confluencias que fallaron por noticias de impacto medio no marcadas en el calendario. Revisé el diario e identifiqué tres errores: no revisé el calendario el miércoles, entré 15 minutos antes del cierre de la killzone, y un trade tenía SL ajustado por debajo del mínimo recomendado. Creé una regla para cada error y reinicié el contador. En el tercer intento logré dos semanas positivas consecutivas (+1,8% y +2,1%).",

  "8-4-1":
    "Configuré la cuenta demo con 100.000$, DD diario 5%, DD total 10%, target +8% en 2 semanas. Semana 7: lunes +0,6%, martes +0,8%, miércoles sin trades (FOMC), jueves +1,0%, viernes +0,4%. Total semana 7: +2,8%, DD máximo diario 0,8%. Semana 8: al llegar al 6,5% acumulado el jueves, reduje riesgo a 0,25% por trade. Viernes solo entré en un setup A+ con 6 confluencias. Total final: +8,3%, sin violar ninguna regla de drawdown. Conclusión: estoy listo para un challenge real de 10.000-25.000$. El punto clave que aprendí: reducir el riesgo al acercarse al objetivo es la diferencia entre pasar y fallar.",

  // ─── FASE 9 ───────────────────────────────────────────────────────────────

  "9-1-3":
    "Cronometré el examen de práctica CMT: respondí las 20 preguntas en 31 minutos (1 minuto 33 segundos por pregunta), dentro del ritmo exigido de 1,8 min/pregunta del examen real. Obtuve 15/20 (75%), superando el umbral de 70% establecido como preparado para el ritmo. Las 5 preguntas falladas fueron sobre el McClellan Oscillator (concepto de breadth), los ciclos de Kitchin vs Juglar (confundí duraciones) y dos preguntas sobre interpretación contrarian del Put/Call Ratio. Programé una sesión de estudio específica sobre indicadores de amplitud de mercado y ciclos económicos para completar la preparación antes del examen CMT real.",

  "9-3-1":
    "Leí los Standards of Practice de la CMT Association en cmtassociation.org. Identifiqué tres situaciones cotidianas donde aplicaría estos principios: (1) Si un amigo me pregunta si debería invertir en la empresa donde trabajo y yo tengo información interna sobre resultados pendientes, debo declinar dar consejo (integridad del mercado e información privilegiada). (2) Si alguien me paga por un análisis y yo tengo una posición abierta en el activo analizado, debo revelar el conflicto de interés antes de entregar el informe (transparencia y conflictos). (3) Si doy una clase de trading, debo actualizar mi formación regularmente y no enseñar estrategias que no puedo demostrar que funcionan con datos reales (competencia y formación continua).",

  "9-3-2":
    "Leí un resumen de 'A Random Walk Down Wall Street' de Malkiel. Sus tres argumentos pro-EMH: los precios son aleatorios (paseos aleatorios), los gestores activos no baten consistentemente al índice, y los patrones del pasado no predicen el futuro. Leí el resumen de Kirkpatrick pro-AT: los patrones de precio se repiten por comportamiento humano predecible (codicia/miedo), la profecía autocumplida (todos ven los mismos niveles) da validez estadística a S/R, y la evidencia empírica muestra que estrategias de momentum y mean reversion generan alpha en horizontes específicos. Mi conclusión personal: los mercados son mayormente eficientes (difícil batirlos de forma consistente) pero las ineficiencias conductuales crean oportunidades explotables de forma sistemática con gestión de riesgo estricta.",
};
