"use client";
import { useState, useEffect, useRef, useCallback } from "react";
import { getMaleSpanishVoice, fixSpanishForTTS } from "@/lib/voiceUtils";

// ============================================================================
// VIDEO LESSON: Animated SVG chart + TTS narration synchronized
// Like a video but generated by code
// ============================================================================

interface VideoStep {
  candles: { o: number; h: number; l: number; c: number }[];
  annotations: { type: "zone" | "label" | "arrow" | "circle"; x?: number; y?: number; x2?: number; y2?: number; price?: number; price2?: number; text?: string; color?: string }[];
  narration: string;
  duration: number; // seconds
}

interface VideoLessonProps {
  title: string;
  steps: VideoStep[];
  pair?: string;
  timeframe?: string;
}

function AnimatedChart({ candles, visibleCount, annotations, W, H }: {
  candles: { o: number; h: number; l: number; c: number }[];
  visibleCount: number;
  annotations: VideoStep["annotations"];
  W: number; H: number;
}) {
  const pad = 20;
  const visible = candles.slice(0, visibleCount);
  if (visible.length === 0) return <svg viewBox={`0 0 ${W} ${H}`} style={{ background: "#131722" }} />;

  const allP = visible.flatMap(c => [c.h, c.l]);
  const minP = Math.min(...allP);
  const maxP = Math.max(...allP);
  const range = maxP - minP || 0.001;
  const cW = Math.min(12, (W - pad - 60) / Math.max(visible.length, 1) - 2);
  const scaleY = (p: number) => pad + ((maxP - p) / range) * (H - pad * 2);
  const scaleX = (i: number) => pad + i * ((W - pad - 60) / Math.max(visible.length, 1));

  // Grid
  const gridPrices = Array.from({ length: 5 }, (_, i) => minP + (range * i) / 4);

  return (
    <svg viewBox={`0 0 ${W} ${H}`} className="w-full" style={{ background: "#131722", borderRadius: 8 }}>
      {/* TradingView-style toolbar simulation */}
      <rect x={0} y={0} width={W} height={18} fill="#1e222d" />
      <text x={8} y={12} fill="#d1d4dc" fontSize={8} fontFamily="monospace" fontWeight="bold">
        {`EURUSD · H4 · OANDA`}
      </text>
      <text x={W - 120} y={12} fill="#787b86" fontSize={7} fontFamily="monospace">O H L C</text>

      {/* Grid */}
      {gridPrices.map((p, i) => (
        <g key={i}>
          <line x1={pad} y1={scaleY(p)} x2={W - 55} y2={scaleY(p)} stroke="#1e222d" strokeWidth={0.5} />
          <text x={W - 53} y={scaleY(p) + 3} fill="#787b86" fontSize={7} fontFamily="monospace">{p.toFixed(4)}</text>
        </g>
      ))}

      {/* Volume bars */}
      {visible.map((c, i) => {
        const x = scaleX(i);
        const isGreen = c.c >= c.o;
        const vol = 5 + Math.random() * 20;
        return <rect key={`v${i}`} x={x} y={H - 15 - vol} width={cW} height={vol} fill={isGreen ? "#26a69a33" : "#ef535033"} />;
      })}

      {/* Candles with animation */}
      {visible.map((c, i) => {
        const x = scaleX(i);
        const isGreen = c.c >= c.o;
        const bodyTop = scaleY(Math.max(c.o, c.c));
        const bodyBot = scaleY(Math.min(c.o, c.c));
        const color = isGreen ? "#26a69a" : "#ef5350";
        const isNew = i === visibleCount - 1;
        return (
          <g key={i} style={isNew ? { animation: "fadeIn 0.3s ease-out" } : undefined}>
            <line x1={x + cW / 2} y1={scaleY(c.h)} x2={x + cW / 2} y2={bodyTop} stroke={color} strokeWidth={0.8} />
            <line x1={x + cW / 2} y1={bodyBot} x2={x + cW / 2} y2={scaleY(c.l)} stroke={color} strokeWidth={0.8} />
            <rect x={x} y={bodyTop} width={cW} height={Math.max(bodyBot - bodyTop, 0.5)} fill={color} />
          </g>
        );
      })}

      {/* Crosshair on last candle */}
      {visible.length > 0 && (() => {
        const last = visible[visible.length - 1];
        const lx = scaleX(visible.length - 1) + cW / 2;
        const ly = scaleY(last.c);
        return (
          <>
            <line x1={lx} y1={20} x2={lx} y2={H - 15} stroke="#787b8633" strokeWidth={0.5} strokeDasharray="3,3" />
            <line x1={pad} y1={ly} x2={W - 55} y2={ly} stroke="#787b8633" strokeWidth={0.5} strokeDasharray="3,3" />
            <rect x={W - 58} y={ly - 8} width={56} height={16} rx={2} fill={last.c >= last.o ? "#26a69a" : "#ef5350"} />
            <text x={W - 55} y={ly + 3} fill="white" fontSize={8} fontFamily="monospace">{last.c.toFixed(4)}</text>
          </>
        );
      })()}

      {/* Annotations */}
      {annotations.map((a, i) => {
        if (a.type === "zone" && a.price && a.price2) {
          return <rect key={i} x={pad} y={scaleY(a.price)} width={W - pad - 60}
            height={scaleY(a.price2) - scaleY(a.price)} fill={`${a.color || "#2962ff"}15`}
            stroke={`${a.color || "#2962ff"}44`} strokeDasharray="4,4"
            style={{ animation: "fadeIn 0.5s ease-out" }} />;
        }
        if (a.type === "label" && a.price && a.text) {
          return <text key={i} x={a.x || pad + 5} y={scaleY(a.price) - 5}
            fill={a.color || "#d1d4dc"} fontSize={9} fontWeight="bold" fontFamily="Inter, sans-serif"
            style={{ animation: "fadeIn 0.5s ease-out" }}>{a.text}</text>;
        }
        if (a.type === "circle" && a.price) {
          const cx = a.x || scaleX(visibleCount - 1) + cW / 2;
          return <circle key={i} cx={cx} cy={scaleY(a.price)} r={5}
            fill={a.color || "#ff9800"} style={{ animation: "pulse 1.5s infinite" }} />;
        }
        if (a.type === "arrow" && a.price && a.price2) {
          const x1 = a.x || pad + 30;
          const x2 = a.x2 || pad + 80;
          return <line key={i} x1={x1} y1={scaleY(a.price)} x2={x2} y2={scaleY(a.price2)}
            stroke={a.color || "#26a69a"} strokeWidth={2} markerEnd="url(#arrowG)"
            style={{ animation: "fadeIn 0.5s ease-out" }} />;
        }
        return null;
      })}

      {/* Arrow marker def */}
      <defs>
        <marker id="arrowG" markerWidth="8" markerHeight="6" refX="8" refY="3" orient="auto">
          <polygon points="0 0, 8 3, 0 6" fill="#26a69a" />
        </marker>
        <style>{`
          @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
          @keyframes pulse { 0%,100% { opacity: 0.6; } 50% { opacity: 1; } }
        `}</style>
      </defs>
    </svg>
  );
}

export default function VideoLesson({ title, steps, pair = "EUR/USD", timeframe = "H4" }: VideoLessonProps) {
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);
  const [candleCount, setCandleCount] = useState(0);
  const [progress, setProgress] = useState(0);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const speechRef = useRef<SpeechSynthesisUtterance | null>(null);

  const step = steps[currentStep];
  const totalDuration = steps.reduce((t, s) => t + s.duration, 0);

  const stopAll = useCallback(() => {
    if (timerRef.current) clearInterval(timerRef.current);
    if (typeof window !== "undefined" && window.speechSynthesis) window.speechSynthesis.cancel();
    setIsPlaying(false);
  }, []);

  const playStep = useCallback((stepIdx: number) => {
    if (stepIdx >= steps.length) { stopAll(); setProgress(100); return; }
    setCurrentStep(stepIdx);
    const s = steps[stepIdx];
    setCandleCount(0);

    // Animate candles appearing one by one
    let candleIdx = 0;
    const candleInterval = (s.duration * 1000) / (s.candles.length + 1);
    timerRef.current = setInterval(() => {
      candleIdx++;
      if (candleIdx <= s.candles.length) {
        setCandleCount(candleIdx);
      } else {
        if (timerRef.current) clearInterval(timerRef.current);
        // Next step after a small pause
        setTimeout(() => playStep(stepIdx + 1), 800);
      }
      // Update progress
      const elapsed = steps.slice(0, stepIdx).reduce((t, st) => t + st.duration, 0) + (candleIdx / s.candles.length) * s.duration;
      setProgress((elapsed / totalDuration) * 100);
    }, candleInterval);

    // TTS narration
    if (typeof window !== "undefined" && window.speechSynthesis) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(fixSpanishForTTS(s.narration));
      const maleVoice = getMaleSpanishVoice();
      if (maleVoice) utterance.voice = maleVoice;
      utterance.lang = "es-ES";
      utterance.rate = 0.9;
      utterance.pitch = 0.9;
      speechRef.current = utterance;
      window.speechSynthesis.speak(utterance);
    }
  }, [steps, totalDuration, stopAll]);

  const play = () => {
    setIsPlaying(true);
    playStep(0);
  };

  const stop = () => {
    stopAll();
    setCurrentStep(0);
    setCandleCount(0);
    setProgress(0);
  };

  useEffect(() => {
    return () => stopAll();
  }, [stopAll]);

  return (
    <div className="bg-[#0d0d15] border border-[#2a2a40] rounded-2xl overflow-hidden">
      {/* Header */}
      <div className="bg-[#1e222d] px-4 py-2 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-2 h-2 rounded-full bg-red-500" />
          <div className="w-2 h-2 rounded-full bg-yellow-500" />
          <div className="w-2 h-2 rounded-full bg-green-500" />
          <span className="text-[#d1d4dc] text-xs font-medium ml-2">{pair} · {timeframe}</span>
        </div>
        <span className="text-[#787b86] text-xs">Video-Leccion Interactiva</span>
      </div>

      {/* Chart area */}
      <div className="p-3">
        <AnimatedChart
          candles={step?.candles || []}
          visibleCount={candleCount}
          annotations={step?.annotations || []}
          W={700} H={320}
        />
      </div>

      {/* Narration text */}
      <div className="px-4 py-3 bg-[#131722] border-t border-[#1e222d] min-h-[60px]">
        <p className="text-[#d1d4dc] text-sm leading-relaxed">
          {step ? step.narration : title}
        </p>
      </div>

      {/* Controls */}
      <div className="px-4 py-3 bg-[#1e222d] flex items-center gap-4">
        {!isPlaying ? (
          <button onClick={play} className="bg-[#2962ff] hover:bg-[#1e53e5] text-white px-5 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition">
            <span>&#9654;</span> Reproducir
          </button>
        ) : (
          <button onClick={stop} className="bg-[#363a45] hover:bg-[#434651] text-[#d1d4dc] px-5 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition">
            <span>&#9632;</span> Detener
          </button>
        )}
        <div className="flex-1 h-1.5 bg-[#131722] rounded-full overflow-hidden">
          <div className="h-full bg-[#2962ff] rounded-full transition-all duration-300" style={{ width: `${progress}%` }} />
        </div>
        <span className="text-[#787b86] text-xs">Paso {currentStep + 1}/{steps.length}</span>
      </div>
    </div>
  );
}

// ============================================================================
// PRE-BUILT VIDEO LESSONS
// ============================================================================

export const VIDEO_LESSONS = {
  supportResistance: {
    title: "Soportes y Resistencias en Accion",
    pair: "EUR/USD",
    timeframe: "H4",
    steps: [
      {
        candles: [
          {o:1.0820,h:1.0835,l:1.0815,c:1.0830},{o:1.0830,h:1.0845,l:1.0825,c:1.0840},
          {o:1.0840,h:1.0855,l:1.0835,c:1.0850},{o:1.0850,h:1.0868,l:1.0845,c:1.0862},
          {o:1.0862,h:1.0878,l:1.0858,c:1.0875},{o:1.0875,h:1.0888,l:1.0870,c:1.0885},
        ],
        annotations: [],
        narration: "Observa como el precio va subiendo vela a vela. Estamos en una tendencia alcista en EUR/USD en temporalidad de 4 horas. Cada vela verde muestra dominio de los compradores.",
        duration: 6,
      },
      {
        candles: [
          {o:1.0820,h:1.0835,l:1.0815,c:1.0830},{o:1.0830,h:1.0845,l:1.0825,c:1.0840},
          {o:1.0840,h:1.0855,l:1.0835,c:1.0850},{o:1.0850,h:1.0868,l:1.0845,c:1.0862},
          {o:1.0862,h:1.0878,l:1.0858,c:1.0875},{o:1.0875,h:1.0888,l:1.0870,c:1.0885},
          {o:1.0885,h:1.0895,l:1.0878,c:1.0882},{o:1.0882,h:1.0890,l:1.0870,c:1.0875},
          {o:1.0875,h:1.0882,l:1.0862,c:1.0865},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0895, price2: 1.0882, color: "#ef5350" },
          { type: "label" as const, price: 1.0898, text: "RESISTENCIA", color: "#ef5350" },
        ],
        narration: "Aqui vemos como el precio llega a la zona de 1.0890 y es RECHAZADO. Las velas empiezan a tener mechas superiores y luego aparecen velas rojas. Esta zona se convierte en RESISTENCIA. El precio no puede superarla.",
        duration: 7,
      },
      {
        candles: [
          {o:1.0820,h:1.0835,l:1.0815,c:1.0830},{o:1.0830,h:1.0845,l:1.0825,c:1.0840},
          {o:1.0840,h:1.0855,l:1.0835,c:1.0850},{o:1.0850,h:1.0868,l:1.0845,c:1.0862},
          {o:1.0862,h:1.0878,l:1.0858,c:1.0875},{o:1.0875,h:1.0888,l:1.0870,c:1.0885},
          {o:1.0885,h:1.0895,l:1.0878,c:1.0882},{o:1.0882,h:1.0890,l:1.0870,c:1.0875},
          {o:1.0875,h:1.0882,l:1.0862,c:1.0865},{o:1.0865,h:1.0870,l:1.0848,c:1.0852},
          {o:1.0852,h:1.0860,l:1.0838,c:1.0842},{o:1.0842,h:1.0855,l:1.0835,c:1.0850},
          {o:1.0850,h:1.0865,l:1.0845,c:1.0862},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0895, price2: 1.0882, color: "#ef5350" },
          { type: "label" as const, price: 1.0898, text: "RESISTENCIA", color: "#ef5350" },
          { type: "zone" as const, price: 1.0850, price2: 1.0835, color: "#26a69a" },
          { type: "label" as const, price: 1.0832, text: "SOPORTE", color: "#26a69a", x: 15 },
          { type: "circle" as const, price: 1.0842, color: "#26a69a", x: 175 },
        ],
        narration: "El precio cae hasta la zona de 1.0835 a 1.0850 y aqui REBOTA. Esta es la zona de SOPORTE. Los compradores defienden este nivel. Fijate en la vela con mecha inferior larga: es un martillo, senal de rechazo. El precio rebota hacia arriba desde el soporte.",
        duration: 8,
      },
      {
        candles: [
          {o:1.0820,h:1.0835,l:1.0815,c:1.0830},{o:1.0830,h:1.0845,l:1.0825,c:1.0840},
          {o:1.0840,h:1.0855,l:1.0835,c:1.0850},{o:1.0850,h:1.0868,l:1.0845,c:1.0862},
          {o:1.0862,h:1.0878,l:1.0858,c:1.0875},{o:1.0875,h:1.0888,l:1.0870,c:1.0885},
          {o:1.0885,h:1.0895,l:1.0878,c:1.0882},{o:1.0882,h:1.0890,l:1.0870,c:1.0875},
          {o:1.0875,h:1.0882,l:1.0862,c:1.0865},{o:1.0865,h:1.0870,l:1.0848,c:1.0852},
          {o:1.0852,h:1.0860,l:1.0838,c:1.0842},{o:1.0842,h:1.0855,l:1.0835,c:1.0850},
          {o:1.0850,h:1.0865,l:1.0845,c:1.0862},{o:1.0862,h:1.0878,l:1.0858,c:1.0875},
          {o:1.0875,h:1.0892,l:1.0872,c:1.0890},{o:1.0890,h:1.0910,l:1.0888,c:1.0908},
          {o:1.0908,h:1.0925,l:1.0905,c:1.0922},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0895, price2: 1.0882, color: "#26a69a" },
          { type: "label" as const, price: 1.0880, text: "RESISTENCIA → SOPORTE (cambio polaridad)", color: "#ff9800", x: 15 },
          { type: "zone" as const, price: 1.0850, price2: 1.0835, color: "#26a69a" },
          { type: "label" as const, price: 1.0832, text: "SOPORTE", color: "#26a69a", x: 15 },
          { type: "circle" as const, price: 1.0892, color: "#ff9800", x: 240 },
        ],
        narration: "Y aqui viene lo mas importante: el precio vuelve a subir y esta vez ROMPE la resistencia con fuerza. Cuando una resistencia se rompe, se convierte en SOPORTE. Esto se llama CAMBIO DE POLARIDAD. Ahora la zona de 1.0885 a 1.0895 que antes frenaba la subida, ahora la sostiene. Este concepto es fundamental en todo el trading.",
        duration: 10,
      },
    ],
  },
  orderBlockTrade: {
    title: "Operacion con Order Block (Setup Completo)",
    pair: "EUR/USD",
    timeframe: "H1",
    steps: [
      {
        candles: [
          {o:1.0880,h:1.0888,l:1.0872,c:1.0878},{o:1.0878,h:1.0885,l:1.0868,c:1.0872},
          {o:1.0872,h:1.0878,l:1.0862,c:1.0865},{o:1.0865,h:1.0872,l:1.0855,c:1.0858},
          {o:1.0858,h:1.0865,l:1.0848,c:1.0852},
        ],
        annotations: [],
        narration: "Estamos observando EUR/USD en temporalidad de 1 hora. El precio esta cayendo, formando una tendencia bajista a corto plazo. Vemos velas rojas consecutivas. Los vendedores dominan.",
        duration: 5,
      },
      {
        candles: [
          {o:1.0880,h:1.0888,l:1.0872,c:1.0878},{o:1.0878,h:1.0885,l:1.0868,c:1.0872},
          {o:1.0872,h:1.0878,l:1.0862,c:1.0865},{o:1.0865,h:1.0872,l:1.0855,c:1.0858},
          {o:1.0858,h:1.0865,l:1.0848,c:1.0852},
          // OB candle
          {o:1.0852,h:1.0858,l:1.0838,c:1.0840},
          // Displacement
          {o:1.0842,h:1.0875,l:1.0840,c:1.0872},{o:1.0872,h:1.0900,l:1.0870,c:1.0898},
          {o:1.0898,h:1.0922,l:1.0895,c:1.0920},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0858, price2: 1.0838, color: "#2962ff" },
          { type: "label" as const, price: 1.0835, text: "ORDER BLOCK (ultima roja antes del movimiento)", color: "#2962ff", x: 15 },
        ],
        narration: "Atencion! Mira esta vela roja grande. Es la ULTIMA vela bajista antes de un movimiento alcista explosivo. Esto es un ORDER BLOCK. Las instituciones acumularon posiciones de compra aqui. Las 3 velas verdes grandes que siguen son el DISPLACEMENT: movimiento agresivo que confirma la intencion real del mercado.",
        duration: 8,
      },
      {
        candles: [
          {o:1.0880,h:1.0888,l:1.0872,c:1.0878},{o:1.0878,h:1.0885,l:1.0868,c:1.0872},
          {o:1.0872,h:1.0878,l:1.0862,c:1.0865},{o:1.0865,h:1.0872,l:1.0855,c:1.0858},
          {o:1.0858,h:1.0865,l:1.0848,c:1.0852},{o:1.0852,h:1.0858,l:1.0838,c:1.0840},
          {o:1.0842,h:1.0875,l:1.0840,c:1.0872},{o:1.0872,h:1.0900,l:1.0870,c:1.0898},
          {o:1.0898,h:1.0922,l:1.0895,c:1.0920},
          // Pullback
          {o:1.0920,h:1.0925,l:1.0905,c:1.0908},{o:1.0908,h:1.0912,l:1.0892,c:1.0895},
          {o:1.0895,h:1.0900,l:1.0878,c:1.0882},{o:1.0882,h:1.0888,l:1.0845,c:1.0848},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0858, price2: 1.0838, color: "#2962ff" },
          { type: "label" as const, price: 1.0835, text: "ORDER BLOCK", color: "#2962ff", x: 15 },
          { type: "circle" as const, price: 1.0848, color: "#26a69a", x: 210 },
          { type: "label" as const, price: 1.0860, text: "Precio retorna al OB → ENTRADA LONG", color: "#26a69a", x: 220 },
        ],
        narration: "Ahora el precio retrocede. Baja vela a vela hasta llegar exactamente a la zona del Order Block. Mira como la ultima vela tiene una mecha inferior que toca el OB y luego cierra con rechazo. ESTE es el momento de entrar en LONG. Stop Loss debajo del Order Block, Take Profit en el maximo anterior o mas alla.",
        duration: 8,
      },
      {
        candles: [
          {o:1.0880,h:1.0888,l:1.0872,c:1.0878},{o:1.0878,h:1.0885,l:1.0868,c:1.0872},
          {o:1.0872,h:1.0878,l:1.0862,c:1.0865},{o:1.0865,h:1.0872,l:1.0855,c:1.0858},
          {o:1.0858,h:1.0865,l:1.0848,c:1.0852},{o:1.0852,h:1.0858,l:1.0838,c:1.0840},
          {o:1.0842,h:1.0875,l:1.0840,c:1.0872},{o:1.0872,h:1.0900,l:1.0870,c:1.0898},
          {o:1.0898,h:1.0922,l:1.0895,c:1.0920},{o:1.0920,h:1.0925,l:1.0905,c:1.0908},
          {o:1.0908,h:1.0912,l:1.0892,c:1.0895},{o:1.0895,h:1.0900,l:1.0878,c:1.0882},
          {o:1.0882,h:1.0888,l:1.0845,c:1.0848},
          // Rally from OB
          {o:1.0848,h:1.0878,l:1.0845,c:1.0875},{o:1.0875,h:1.0905,l:1.0872,c:1.0902},
          {o:1.0902,h:1.0928,l:1.0900,c:1.0925},{o:1.0925,h:1.0948,l:1.0922,c:1.0945},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0858, price2: 1.0838, color: "#2962ff" },
          { type: "label" as const, price: 1.0948, text: "TP alcanzado: +100 pips", color: "#26a69a", x: 250 },
          { type: "label" as const, price: 1.0835, text: "SL: -15 pips | R:R = 1:6.7", color: "#ef5350", x: 15 },
        ],
        narration: "Y aqui tienes el resultado. El precio reboto perfectamente desde el Order Block y subio con fuerza. Si entraste en la zona del OB con un Stop Loss de 15 pips y el precio subio 100 pips, tu ratio riesgo beneficio fue de 1 a 6.7. Excelente. Este es el poder de operar con Smart Money Concepts: entradas precisas con ratios de riesgo beneficio muy favorables.",
        duration: 9,
      },
    ],
  },

  // VIDEO 3: Candle Patterns
  candlePatterns: {
    title: "Patrones de Velas en Accion",
    pair: "GBP/USD", timeframe: "H4",
    steps: [
      {
        candles: [
          {o:1.2650,h:1.2665,l:1.2640,c:1.2658},{o:1.2658,h:1.2670,l:1.2648,c:1.2645},
          {o:1.2645,h:1.2655,l:1.2630,c:1.2635},{o:1.2635,h:1.2642,l:1.2618,c:1.2622},
          {o:1.2622,h:1.2630,l:1.2608,c:1.2612},
        ],
        annotations: [],
        narration: "Estamos en GBP/USD en temporalidad de 4 horas. El precio esta cayendo con velas rojas consecutivas. Los vendedores dominan. Pero observa lo que pasa en la siguiente vela cuando llega a una zona de soporte.",
        duration: 6,
      },
      {
        candles: [
          {o:1.2650,h:1.2665,l:1.2640,c:1.2658},{o:1.2658,h:1.2670,l:1.2648,c:1.2645},
          {o:1.2645,h:1.2655,l:1.2630,c:1.2635},{o:1.2635,h:1.2642,l:1.2618,c:1.2622},
          {o:1.2622,h:1.2630,l:1.2608,c:1.2612},
          // HAMMER
          {o:1.2612,h:1.2620,l:1.2585,c:1.2618},
        ],
        annotations: [
          { type: "zone" as const, price: 1.2620, price2: 1.2600, color: "#26a69a" },
          { type: "label" as const, price: 1.2597, text: "SOPORTE", color: "#26a69a", x: 15 },
          { type: "circle" as const, price: 1.2618, color: "#ff9800", x: 100 },
          { type: "label" as const, price: 1.2625, text: "MARTILLO! Mecha larga inferior = rechazo", color: "#ff9800", x: 110 },
        ],
        narration: "Mira esta vela. Tiene un cuerpo pequeno arriba y una mecha inferior MUY larga. Esto es un MARTILLO. Los vendedores empujaron el precio hacia abajo pero los compradores lo devolvieron con fuerza. La mecha larga muestra RECHAZO del soporte. Esta es una senal alcista clasica.",
        duration: 8,
      },
      {
        candles: [
          {o:1.2650,h:1.2665,l:1.2640,c:1.2658},{o:1.2658,h:1.2670,l:1.2648,c:1.2645},
          {o:1.2645,h:1.2655,l:1.2630,c:1.2635},{o:1.2635,h:1.2642,l:1.2618,c:1.2622},
          {o:1.2622,h:1.2630,l:1.2608,c:1.2612},{o:1.2612,h:1.2620,l:1.2585,c:1.2618},
          // ENGULFING
          {o:1.2615,h:1.2655,l:1.2612,c:1.2652},
        ],
        annotations: [
          { type: "zone" as const, price: 1.2620, price2: 1.2600, color: "#26a69a" },
          { type: "circle" as const, price: 1.2652, color: "#26a69a", x: 115 },
          { type: "label" as const, price: 1.2660, text: "ENVOLVENTE ALCISTA! Verde grande envuelve roja", color: "#26a69a", x: 120 },
        ],
        narration: "Y ahora viene la confirmacion definitiva: una vela verde GRANDE que envuelve completamente a la roja anterior. Esto es un patron ENVOLVENTE ALCISTA. Martillo mas envolvente en soporte es un combo extremadamente poderoso. Las probabilidades de subida son muy altas.",
        duration: 7,
      },
      {
        candles: [
          {o:1.2650,h:1.2665,l:1.2640,c:1.2658},{o:1.2658,h:1.2670,l:1.2648,c:1.2645},
          {o:1.2645,h:1.2655,l:1.2630,c:1.2635},{o:1.2635,h:1.2642,l:1.2618,c:1.2622},
          {o:1.2622,h:1.2630,l:1.2608,c:1.2612},{o:1.2612,h:1.2620,l:1.2585,c:1.2618},
          {o:1.2615,h:1.2655,l:1.2612,c:1.2652},
          {o:1.2652,h:1.2678,l:1.2648,c:1.2675},{o:1.2675,h:1.2698,l:1.2672,c:1.2695},
          {o:1.2695,h:1.2715,l:1.2690,c:1.2712},
        ],
        annotations: [
          { type: "label" as const, price: 1.2718, text: "Rally de +100 pips tras la confirmacion", color: "#26a69a", x: 150 },
        ],
        narration: "Resultado: el precio subio 100 pips desde la zona de soporte. La leccion clave es que los patrones de velas SOLO son fiables cuando aparecen en un nivel importante, como un soporte fuerte. Un martillo en medio de la nada no significa nada. Un martillo en soporte con envolvente de confirmacion es una senal de alta probabilidad.",
        duration: 8,
      },
    ],
  },

  // VIDEO 4: Liquidity Sweep
  liquiditySweep: {
    title: "Caza de Liquidez: Asi te Roban tu Stop Loss",
    pair: "EUR/USD", timeframe: "M15",
    steps: [
      {
        candles: [
          {o:1.0850,h:1.0862,l:1.0845,c:1.0858},{o:1.0858,h:1.0868,l:1.0852,c:1.0860},
          {o:1.0860,h:1.0870,l:1.0848,c:1.0852},{o:1.0852,h:1.0862,l:1.0845,c:1.0858},
          {o:1.0858,h:1.0865,l:1.0848,c:1.0850},{o:1.0850,h:1.0860,l:1.0842,c:1.0855},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0850, price2: 1.0842, color: "#ff9800" },
          { type: "label" as const, price: 1.0839, text: "Equal Lows = LIQUIDEZ acumulada (SL de traders retail)", color: "#ff9800", x: 15 },
        ],
        narration: "Observa estos minimos iguales. El precio toca 1.0842 a 1.0845 tres veces sin romper. Los traders retail ven un soporte fuerte y ponen sus Stop Loss justo debajo, en 1.0835 a 1.0840. Esto crea una PISCINA DE LIQUIDEZ. Las instituciones ven esos Stop Loss como combustible.",
        duration: 8,
      },
      {
        candles: [
          {o:1.0850,h:1.0862,l:1.0845,c:1.0858},{o:1.0858,h:1.0868,l:1.0852,c:1.0860},
          {o:1.0860,h:1.0870,l:1.0848,c:1.0852},{o:1.0852,h:1.0862,l:1.0845,c:1.0858},
          {o:1.0858,h:1.0865,l:1.0848,c:1.0850},{o:1.0850,h:1.0860,l:1.0842,c:1.0855},
          // SWEEP
          {o:1.0855,h:1.0858,l:1.0825,c:1.0830},
          {o:1.0830,h:1.0835,l:1.0818,c:1.0820},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0850, price2: 1.0842, color: "#ff9800" },
          { type: "circle" as const, price: 1.0818, color: "#ef5350", x: 130 },
          { type: "label" as const, price: 1.0815, text: "SWEEP! El precio barre todos los Stop Loss", color: "#ef5350", x: 15 },
        ],
        narration: "Y aqui viene la caza. El precio cae BRUSCAMENTE por debajo de los equal lows. Activa TODOS los Stop Loss de los traders que estaban en long. Esos SL son ordenes de venta que les dan a las instituciones la liquidez que necesitan para sus ordenes de compra masivas. Fijate: la caida es rapida y agresiva.",
        duration: 8,
      },
      {
        candles: [
          {o:1.0850,h:1.0862,l:1.0845,c:1.0858},{o:1.0858,h:1.0868,l:1.0852,c:1.0860},
          {o:1.0860,h:1.0870,l:1.0848,c:1.0852},{o:1.0852,h:1.0862,l:1.0845,c:1.0858},
          {o:1.0858,h:1.0865,l:1.0848,c:1.0850},{o:1.0850,h:1.0860,l:1.0842,c:1.0855},
          {o:1.0855,h:1.0858,l:1.0825,c:1.0830},{o:1.0830,h:1.0835,l:1.0818,c:1.0820},
          // REVERSAL
          {o:1.0820,h:1.0858,l:1.0815,c:1.0855},
          {o:1.0855,h:1.0885,l:1.0852,c:1.0882},
          {o:1.0882,h:1.0910,l:1.0878,c:1.0908},
          {o:1.0908,h:1.0935,l:1.0905,c:1.0932},
        ],
        annotations: [
          { type: "circle" as const, price: 1.0855, color: "#26a69a", x: 140 },
          { type: "label" as const, price: 1.0938, text: "Rally de +115 pips tras el sweep", color: "#26a69a", x: 180 },
          { type: "label" as const, price: 1.0810, text: "El que entendio el sweep, compro aqui", color: "#ff9800", x: 15 },
        ],
        narration: "Y mira lo que pasa inmediatamente despues. Vela de reversal gigante: martillo con mecha larga que muestra rechazo total de los precios bajos. Luego tres velas verdes grandes. El precio sube 115 pips. Los traders retail perdieron sus posiciones en el sweep. El trader que entiende Smart Money vio el sweep, espero la confirmacion, entro en long, y gano. Esta es la diferencia entre operar como retail y operar como institucional.",
        duration: 10,
      },
    ],
  },

  // VIDEO 5: Power of 3 (AMD)
  powerOf3: {
    title: "Power of 3: Asi se Mueve el Mercado CADA DIA",
    pair: "EUR/USD", timeframe: "M15",
    steps: [
      {
        candles: [
          {o:1.0850,h:1.0858,l:1.0845,c:1.0852},{o:1.0852,h:1.0856,l:1.0848,c:1.0850},
          {o:1.0850,h:1.0855,l:1.0846,c:1.0853},{o:1.0853,h:1.0858,l:1.0848,c:1.0855},
          {o:1.0855,h:1.0860,l:1.0850,c:1.0852},{o:1.0852,h:1.0858,l:1.0848,c:1.0856},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0860, price2: 1.0845, color: "#6366f1" },
          { type: "label" as const, price: 1.0862, text: "ASIA: Rango pequeno (acumulacion)", color: "#6366f1", x: 15 },
        ],
        narration: "Son las 2 de la madrugada hora de Espana. Sesion asiatica. El precio se mueve en un rango muy estrecho entre 1.0845 y 1.0860. Solo 15 pips de rango. Esto es la fase de ACUMULACION. Las instituciones estan colocando sus ordenes silenciosamente mientras el mercado parece dormido.",
        duration: 8,
      },
      {
        candles: [
          {o:1.0850,h:1.0858,l:1.0845,c:1.0852},{o:1.0852,h:1.0856,l:1.0848,c:1.0850},
          {o:1.0850,h:1.0855,l:1.0846,c:1.0853},{o:1.0853,h:1.0858,l:1.0848,c:1.0855},
          {o:1.0855,h:1.0860,l:1.0850,c:1.0852},{o:1.0852,h:1.0858,l:1.0848,c:1.0856},
          // LONDON MANIPULATION - breaks below Asia low
          {o:1.0856,h:1.0858,l:1.0838,c:1.0840},
          {o:1.0840,h:1.0842,l:1.0828,c:1.0830},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0860, price2: 1.0845, color: "#6366f1" },
          { type: "label" as const, price: 1.0862, text: "ASIA", color: "#6366f1", x: 15 },
          { type: "circle" as const, price: 1.0828, color: "#ef5350", x: 130 },
          { type: "label" as const, price: 1.0825, text: "LONDON: Rompe Asia Low = MANIPULACION", color: "#ef5350", x: 15 },
        ],
        narration: "Son las 8 de la manana. Abre la sesion de Londres. El precio cae BRUSCAMENTE y rompe el minimo del rango asiatico. Los traders retail que compraron en Asia ven sus Stop Loss activados. Esta es la fase de MANIPULACION. London esta cazando liquidez debajo del rango de Asia. NO sigas esta ruptura, es una TRAMPA.",
        duration: 9,
      },
      {
        candles: [
          {o:1.0850,h:1.0858,l:1.0845,c:1.0852},{o:1.0852,h:1.0856,l:1.0848,c:1.0850},
          {o:1.0850,h:1.0855,l:1.0846,c:1.0853},{o:1.0853,h:1.0858,l:1.0848,c:1.0855},
          {o:1.0855,h:1.0860,l:1.0850,c:1.0852},{o:1.0852,h:1.0858,l:1.0848,c:1.0856},
          {o:1.0856,h:1.0858,l:1.0838,c:1.0840},{o:1.0840,h:1.0842,l:1.0828,c:1.0830},
          // REVERSAL + NY DISTRIBUTION
          {o:1.0830,h:1.0862,l:1.0825,c:1.0858},
          {o:1.0858,h:1.0882,l:1.0855,c:1.0880},
          {o:1.0880,h:1.0905,l:1.0878,c:1.0902},
          {o:1.0902,h:1.0928,l:1.0900,c:1.0925},
          {o:1.0925,h:1.0945,l:1.0920,c:1.0940},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0860, price2: 1.0845, color: "#6366f1" },
          { type: "label" as const, price: 1.0945, text: "NY: DISTRIBUCION - movimiento REAL del dia (+115 pips)", color: "#26a69a", x: 100 },
          { type: "label" as const, price: 1.0825, text: "Entrada aqui tras ver el sweep + reversal", color: "#ff9800", x: 15 },
        ],
        narration: "Y aqui viene la verdad. Despues de la caza de liquidez, el precio se GIRA completamente. Vela de reversal gigante, y luego la sesion de Nueva York impulsa el precio hacia arriba con fuerza. El movimiento real del dia es ALCISTA, contrario a la manipulacion de London. 115 pips de subida. Este patron se repite CADA DIA. Acumulacion en Asia, manipulacion en London, distribucion en Nueva York. Una vez que lo ves, no puedes dejar de verlo.",
        duration: 10,
      },
    ],
  },

  // VIDEO 6: RSI Divergence
  rsiDivergence: {
    title: "Divergencia del RSI: La Senal que Predice Giros",
    pair: "EUR/USD", timeframe: "H4",
    steps: [
      {
        candles: [
          {o:1.0800,h:1.0818,l:1.0795,c:1.0815},{o:1.0815,h:1.0835,l:1.0812,c:1.0832},
          {o:1.0832,h:1.0852,l:1.0828,c:1.0848},{o:1.0848,h:1.0868,l:1.0845,c:1.0865},
          {o:1.0865,h:1.0882,l:1.0860,c:1.0878},{o:1.0878,h:1.0895,l:1.0875,c:1.0892},
          // First high
          {o:1.0892,h:1.0910,l:1.0888,c:1.0905},
        ],
        annotations: [
          { type: "circle" as const, price: 1.0910, color: "#2962ff", x: 115 },
          { type: "label" as const, price: 1.0915, text: "Maximo 1: 1.0910 | RSI: 78", color: "#2962ff", x: 120 },
        ],
        narration: "El precio sube con fuerza hasta 1.0910. El RSI esta en 78, en zona de sobrecompra. Esto por si solo NO es senal de venta. El RSI puede quedarse en sobrecompra mucho tiempo en tendencia fuerte. La clave es lo que pasa despues.",
        duration: 7,
      },
      {
        candles: [
          {o:1.0800,h:1.0818,l:1.0795,c:1.0815},{o:1.0815,h:1.0835,l:1.0812,c:1.0832},
          {o:1.0832,h:1.0852,l:1.0828,c:1.0848},{o:1.0848,h:1.0868,l:1.0845,c:1.0865},
          {o:1.0865,h:1.0882,l:1.0860,c:1.0878},{o:1.0878,h:1.0895,l:1.0875,c:1.0892},
          {o:1.0892,h:1.0910,l:1.0888,c:1.0905},
          // Pullback
          {o:1.0905,h:1.0908,l:1.0885,c:1.0888},{o:1.0888,h:1.0895,l:1.0878,c:1.0882},
          // Second higher high
          {o:1.0882,h:1.0890,l:1.0875,c:1.0888},{o:1.0888,h:1.0902,l:1.0885,c:1.0900},
          {o:1.0900,h:1.0920,l:1.0898,c:1.0918},
        ],
        annotations: [
          { type: "circle" as const, price: 1.0910, color: "#2962ff", x: 115 },
          { type: "label" as const, price: 1.0912, text: "Maximo 1: RSI 78", color: "#2962ff", x: 120 },
          { type: "circle" as const, price: 1.0920, color: "#ef5350", x: 195 },
          { type: "label" as const, price: 1.0925, text: "Maximo 2: precio MAS ALTO pero RSI solo 68", color: "#ef5350", x: 15 },
        ],
        narration: "Ahora el precio sube AUN MAS hasta 1.0920, un maximo mas alto. PERO mira el RSI: solo marca 68. Antes marco 78 con un precio menor. El precio sube pero el RSI BAJA. Esto es una DIVERGENCIA BAJISTA. El momentum se esta agotando. El precio sigue subiendo por inercia pero la fuerza detras ya no esta.",
        duration: 9,
      },
      {
        candles: [
          {o:1.0800,h:1.0818,l:1.0795,c:1.0815},{o:1.0815,h:1.0835,l:1.0812,c:1.0832},
          {o:1.0832,h:1.0852,l:1.0828,c:1.0848},{o:1.0848,h:1.0868,l:1.0845,c:1.0865},
          {o:1.0865,h:1.0882,l:1.0860,c:1.0878},{o:1.0878,h:1.0895,l:1.0875,c:1.0892},
          {o:1.0892,h:1.0910,l:1.0888,c:1.0905},{o:1.0905,h:1.0908,l:1.0885,c:1.0888},
          {o:1.0888,h:1.0895,l:1.0878,c:1.0882},{o:1.0882,h:1.0890,l:1.0875,c:1.0888},
          {o:1.0888,h:1.0902,l:1.0885,c:1.0900},{o:1.0900,h:1.0920,l:1.0898,c:1.0918},
          // Drop after divergence
          {o:1.0918,h:1.0920,l:1.0898,c:1.0900},{o:1.0900,h:1.0905,l:1.0878,c:1.0880},
          {o:1.0880,h:1.0885,l:1.0858,c:1.0862},{o:1.0862,h:1.0868,l:1.0838,c:1.0842},
        ],
        annotations: [
          { type: "label" as const, price: 1.0835, text: "Caida de 80 pips tras la divergencia bajista", color: "#ef5350", x: 200 },
        ],
        narration: "Y mira el resultado. Despues de la divergencia, el precio cae 80 pips. La divergencia del RSI predijo correctamente el giro. Recuerda: la divergencia es una ADVERTENCIA de que el momentum se agota. No es senal de entrada directa. Necesitas confirmacion: un BOS, un patron de vela de rechazo, o un Order Block que coincida. La divergencia mas estructura es un combo mortal.",
        duration: 9,
      },
    ],
  },

  // VIDEO 7: Fibonacci OTE Entry
  fibonacciOTE: {
    title: "Entrada con Fibonacci OTE: El Setup Institucional",
    pair: "EUR/USD", timeframe: "H4",
    steps: [
      {
        candles: [
          {o:1.0780,h:1.0798,l:1.0775,c:1.0795},{o:1.0795,h:1.0815,l:1.0792,c:1.0812},
          {o:1.0812,h:1.0835,l:1.0808,c:1.0832},{o:1.0832,h:1.0855,l:1.0828,c:1.0852},
          {o:1.0852,h:1.0872,l:1.0848,c:1.0868},{o:1.0868,h:1.0892,l:1.0865,c:1.0890},
          {o:1.0890,h:1.0912,l:1.0888,c:1.0908},
        ],
        annotations: [
          { type: "label" as const, price: 1.0775, text: "Swing Low: 1.0775", color: "#42a5f5", x: 15 },
          { type: "label" as const, price: 1.0915, text: "Swing High: 1.0912", color: "#26a69a", x: 100 },
        ],
        narration: "Tenemos un movimiento impulsivo alcista de 1.0775 a 1.0912. Son 137 pips de impulso. Ahora aplicamos Fibonacci desde el minimo al maximo para encontrar la zona de retroceso optima. Los niveles clave son 38.2 por ciento, 50 por ciento, y la zona OTE entre 61.8 y 78.6 por ciento.",
        duration: 7,
      },
      {
        candles: [
          {o:1.0780,h:1.0798,l:1.0775,c:1.0795},{o:1.0795,h:1.0815,l:1.0792,c:1.0812},
          {o:1.0812,h:1.0835,l:1.0808,c:1.0832},{o:1.0832,h:1.0855,l:1.0828,c:1.0852},
          {o:1.0852,h:1.0872,l:1.0848,c:1.0868},{o:1.0868,h:1.0892,l:1.0865,c:1.0890},
          {o:1.0890,h:1.0912,l:1.0888,c:1.0908},
          // Retracement
          {o:1.0908,h:1.0910,l:1.0888,c:1.0892},{o:1.0892,h:1.0898,l:1.0872,c:1.0878},
          {o:1.0878,h:1.0882,l:1.0858,c:1.0862},{o:1.0862,h:1.0868,l:1.0845,c:1.0848},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0865, price2: 1.0835, color: "#ff9800" },
          { type: "label" as const, price: 1.0830, text: "ZONA OTE: 61.8% - 78.6% de Fibonacci", color: "#ff9800", x: 15 },
        ],
        narration: "El precio empieza a retroceder. Baja vela a vela. La zona OTE, entre 61.8 y 78.6 por ciento del movimiento, esta entre 1.0835 y 1.0865. Esta es la zona donde las instituciones buscan reentrar en la tendencia. Esperamos pacientemente a que el precio llegue ahi.",
        duration: 8,
      },
      {
        candles: [
          {o:1.0780,h:1.0798,l:1.0775,c:1.0795},{o:1.0795,h:1.0815,l:1.0792,c:1.0812},
          {o:1.0812,h:1.0835,l:1.0808,c:1.0832},{o:1.0832,h:1.0855,l:1.0828,c:1.0852},
          {o:1.0852,h:1.0872,l:1.0848,c:1.0868},{o:1.0868,h:1.0892,l:1.0865,c:1.0890},
          {o:1.0890,h:1.0912,l:1.0888,c:1.0908},{o:1.0908,h:1.0910,l:1.0888,c:1.0892},
          {o:1.0892,h:1.0898,l:1.0872,c:1.0878},{o:1.0878,h:1.0882,l:1.0858,c:1.0862},
          {o:1.0862,h:1.0868,l:1.0845,c:1.0848},
          // Pin bar at OTE
          {o:1.0848,h:1.0868,l:1.0832,c:1.0865},
          // Continuation
          {o:1.0865,h:1.0892,l:1.0862,c:1.0890},{o:1.0890,h:1.0918,l:1.0888,c:1.0915},
          {o:1.0915,h:1.0942,l:1.0912,c:1.0940},{o:1.0940,h:1.0960,l:1.0935,c:1.0955},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0865, price2: 1.0835, color: "#ff9800" },
          { type: "circle" as const, price: 1.0865, color: "#26a69a", x: 190 },
          { type: "label" as const, price: 1.0828, text: "Pin Bar en OTE = ENTRADA LONG | SL: 1.0828 | TP: 1.0955", color: "#26a69a", x: 15 },
          { type: "label" as const, price: 1.0960, text: "R:R = 1:3.4 | +127 pips", color: "#26a69a", x: 200 },
        ],
        narration: "El precio llega a la zona OTE y forma un PIN BAR con mecha inferior larga. Rechazo perfecto del nivel 61.8 de Fibonacci. Entramos LONG con Stop Loss debajo de la zona OTE en 1.0828 y Take Profit en 1.0955. Resultado: 127 pips de ganancia con un ratio riesgo beneficio de 1 a 3.4. Este setup de Fibonacci mas OTE mas patron de rechazo es uno de los mas rentables y fiables que existen.",
        duration: 10,
      },
    ],
  },

  // VIDEO 8: Risk Management in Action
  riskManagement: {
    title: "Gestion de Riesgo: Asi Sobrevives en Trading",
    pair: "EUR/USD", timeframe: "H1",
    steps: [
      {
        candles: [
          {o:1.0850,h:1.0865,l:1.0845,c:1.0860},{o:1.0860,h:1.0872,l:1.0855,c:1.0868},
        ],
        annotations: [
          { type: "label" as const, price: 1.0875, text: "Cuenta: 10,000$ | Riesgo: 1% = 100$", color: "#d1d4dc", x: 15 },
          { type: "label" as const, price: 1.0840, text: "SL: 30 pips | Lotes: 100$ / (30 x 10$) = 0.33", color: "#ff9800", x: 15 },
        ],
        narration: "Tienes una cuenta de 10,000 dolares. Tu regla es arriesgar el 1 por ciento por trade, es decir 100 dolares. Tu Stop Loss esta a 30 pips. El calculo de position sizing es: 100 dolares dividido entre 30 pips por 10 dolares por pip, igual a 0.33 lotes. SIEMPRE calcula esto ANTES de cada trade.",
        duration: 8,
      },
      {
        candles: [
          {o:1.0850,h:1.0865,l:1.0845,c:1.0860},{o:1.0860,h:1.0872,l:1.0855,c:1.0868},
          {o:1.0868,h:1.0875,l:1.0858,c:1.0862},{o:1.0862,h:1.0870,l:1.0845,c:1.0848},
          {o:1.0848,h:1.0852,l:1.0832,c:1.0835},
        ],
        annotations: [
          { type: "label" as const, price: 1.0830, text: "Trade 1: PERDIDA -100$ | Balance: 9,900$", color: "#ef5350", x: 15 },
        ],
        narration: "Primer trade: PERDIDA. El Stop Loss se activo. Perdiste exactamente 100 dolares, el 1 por ciento de tu cuenta. Balance queda en 9,900. Esto es NORMAL. Es parte del juego. La clave es que la perdida esta CONTROLADA. No destruyo tu cuenta.",
        duration: 7,
      },
      {
        candles: [
          {o:1.0850,h:1.0865,l:1.0845,c:1.0860},{o:1.0860,h:1.0872,l:1.0855,c:1.0868},
          {o:1.0868,h:1.0875,l:1.0858,c:1.0862},{o:1.0862,h:1.0870,l:1.0845,c:1.0848},
          {o:1.0848,h:1.0852,l:1.0832,c:1.0835},
          {o:1.0835,h:1.0860,l:1.0830,c:1.0858},{o:1.0858,h:1.0885,l:1.0855,c:1.0882},
          {o:1.0882,h:1.0912,l:1.0880,c:1.0908},
        ],
        annotations: [
          { type: "label" as const, price: 1.0915, text: "Trade 2: GANANCIA +200$ (R:R 1:2) | Balance: 10,100$", color: "#26a69a", x: 15 },
          { type: "label" as const, price: 1.0825, text: "1 perdida + 1 ganancia con R:R 1:2 = BENEFICIO NETO +100$", color: "#ff9800", x: 15 },
        ],
        narration: "Segundo trade: GANANCIA. Con ratio 1:2, ganaste 200 dolares. Balance ahora es 10,100 dolares. Fijate: perdiste 1 trade y ganaste 1 trade. Resultado neto: mas 100 dolares de beneficio. Con ratio 1:2, solo necesitas ganar 1 de cada 3 para ser rentable. ESTO es el poder de la gestion de riesgo. No se trata de acertar siempre. Se trata de que cuando aciertas, ganes mas de lo que pierdes cuando fallas.",
        duration: 10,
      },
    ],
  },

  // VIDEO 9: Prop Firm Challenge Setup
  propFirmSetup: {
    title: "Setup de Trading para Challenge de Prop Firm",
    pair: "EUR/USD", timeframe: "H1",
    steps: [
      {
        candles: [
          {o:1.0860,h:1.0872,l:1.0855,c:1.0868},{o:1.0868,h:1.0878,l:1.0862,c:1.0875},
          {o:1.0875,h:1.0888,l:1.0872,c:1.0885},{o:1.0885,h:1.0895,l:1.0878,c:1.0882},
          {o:1.0882,h:1.0890,l:1.0868,c:1.0872},
        ],
        annotations: [
          { type: "label" as const, price: 1.0898, text: "Challenge 100K FTMO | Objetivo: +8,000$ | DD max: 5,000$/dia", color: "#ff9800", x: 15 },
          { type: "label" as const, price: 1.0863, text: "Riesgo por trade: 0.5% = 500$ | R:R: 1:2 minimo", color: "#d1d4dc", x: 15 },
        ],
        narration: "Estas en un challenge de FTMO de 100,000 dolares. Objetivo: ganar 8,000 dolares. Drawdown maximo diario: 5,000 dolares. Tu riesgo por trade: 0.5 por ciento, es decir 500 dolares. Con ratio 1:2, cada ganadora te da 1,000 dolares. Solo necesitas 8 trades ganadores netos para pasar. En 4 semanas, eso es 2 por semana. Totalmente alcanzable con disciplina.",
        duration: 9,
      },
      {
        candles: [
          {o:1.0860,h:1.0872,l:1.0855,c:1.0868},{o:1.0868,h:1.0878,l:1.0862,c:1.0875},
          {o:1.0875,h:1.0888,l:1.0872,c:1.0885},{o:1.0885,h:1.0895,l:1.0878,c:1.0882},
          {o:1.0882,h:1.0890,l:1.0868,c:1.0872},{o:1.0872,h:1.0880,l:1.0858,c:1.0862},
          {o:1.0862,h:1.0870,l:1.0848,c:1.0852},
          // Entry at OB
          {o:1.0852,h:1.0875,l:1.0848,c:1.0872},
          {o:1.0872,h:1.0898,l:1.0870,c:1.0895},
          {o:1.0895,h:1.0918,l:1.0892,c:1.0915},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0862, price2: 1.0848, color: "#2962ff" },
          { type: "label" as const, price: 1.0845, text: "OB alcista | Entry: 1.0852 | SL: 1.0840 | TP: 1.0876", color: "#2962ff", x: 15 },
          { type: "label" as const, price: 1.0920, text: "WIN +1,000$ | Balance: 101,000$ (+1%)", color: "#26a69a", x: 150 },
        ],
        narration: "Esperas pacientemente a que el precio retroceda a un Order Block en zona discount. Entras en 1.0852, Stop Loss en 1.0840 que son 12 pips, y Take Profit en 1.0876 que son 24 pips, ratio 1:2. El trade gana. Plus 1,000 dolares. Balance: 101,000. Ya llevas el 1 por ciento del objetivo en UN solo trade bien ejecutado. Asi se pasa un challenge: trades selectivos con buena gestion de riesgo.",
        duration: 10,
      },
      {
        candles: [
          {o:1.0860,h:1.0872,l:1.0855,c:1.0868},{o:1.0868,h:1.0878,l:1.0862,c:1.0875},
          {o:1.0875,h:1.0888,l:1.0872,c:1.0885},{o:1.0885,h:1.0895,l:1.0878,c:1.0882},
          {o:1.0882,h:1.0890,l:1.0868,c:1.0872},{o:1.0872,h:1.0880,l:1.0858,c:1.0862},
          {o:1.0862,h:1.0870,l:1.0848,c:1.0852},{o:1.0852,h:1.0875,l:1.0848,c:1.0872},
          {o:1.0872,h:1.0898,l:1.0870,c:1.0895},{o:1.0895,h:1.0918,l:1.0892,c:1.0915},
          {o:1.0915,h:1.0920,l:1.0898,c:1.0902},{o:1.0902,h:1.0908,l:1.0888,c:1.0892},
        ],
        annotations: [
          { type: "label" as const, price: 1.0925, text: "Semana 1: +2,500$ | Semana 2: +2,000$ | Semana 3: +2,000$", color: "#26a69a", x: 15 },
          { type: "label" as const, price: 1.0885, text: "Semana 4: reduce riesgo a 0.25% para PROTEGER ganancias", color: "#ff9800", x: 15 },
          { type: "label" as const, price: 1.0848, text: "RESULTADO: +8,500$ en 4 semanas = CHALLENGE PASADO!", color: "#26a69a", x: 100 },
        ],
        narration: "Asi se ve un challenge exitoso: semana 1 ganas 2,500, semana 2 ganas 2,000, ya llevas 4,500. En semana 3 sumas 2,000 mas y llevas 6,500. En semana 4 REDUCES el riesgo a 0.25 por ciento porque solo necesitas 1,500 mas. Proteges lo ganado. Terminas con 8,500 dolares de beneficio. Challenge PASADO. Nunca superaste el drawdown diario. Todo con disciplina, paciencia, y gestion de riesgo. Asi se hace.",
        duration: 10,
      },
    ],
  },
};
