"use client";
import { useState, useEffect, useRef, useCallback } from "react";

// ============================================================================
// VIDEO LESSON: Animated SVG chart + TTS narration synchronized
// Like a video but generated by code
// ============================================================================

interface VideoStep {
  candles: { o: number; h: number; l: number; c: number }[];
  annotations: { type: "zone" | "label" | "arrow" | "circle"; x?: number; y?: number; x2?: number; y2?: number; price?: number; price2?: number; text?: string; color?: string }[];
  narration: string;
  duration: number; // seconds
}

interface VideoLessonProps {
  title: string;
  steps: VideoStep[];
  pair?: string;
  timeframe?: string;
}

function AnimatedChart({ candles, visibleCount, annotations, W, H }: {
  candles: { o: number; h: number; l: number; c: number }[];
  visibleCount: number;
  annotations: VideoStep["annotations"];
  W: number; H: number;
}) {
  const pad = 20;
  const visible = candles.slice(0, visibleCount);
  if (visible.length === 0) return <svg viewBox={`0 0 ${W} ${H}`} style={{ background: "#131722" }} />;

  const allP = visible.flatMap(c => [c.h, c.l]);
  const minP = Math.min(...allP);
  const maxP = Math.max(...allP);
  const range = maxP - minP || 0.001;
  const cW = Math.min(12, (W - pad - 60) / Math.max(visible.length, 1) - 2);
  const scaleY = (p: number) => pad + ((maxP - p) / range) * (H - pad * 2);
  const scaleX = (i: number) => pad + i * ((W - pad - 60) / Math.max(visible.length, 1));

  // Grid
  const gridPrices = Array.from({ length: 5 }, (_, i) => minP + (range * i) / 4);

  return (
    <svg viewBox={`0 0 ${W} ${H}`} className="w-full" style={{ background: "#131722", borderRadius: 8 }}>
      {/* TradingView-style toolbar simulation */}
      <rect x={0} y={0} width={W} height={18} fill="#1e222d" />
      <text x={8} y={12} fill="#d1d4dc" fontSize={8} fontFamily="monospace" fontWeight="bold">
        {`EURUSD · H4 · OANDA`}
      </text>
      <text x={W - 120} y={12} fill="#787b86" fontSize={7} fontFamily="monospace">O H L C</text>

      {/* Grid */}
      {gridPrices.map((p, i) => (
        <g key={i}>
          <line x1={pad} y1={scaleY(p)} x2={W - 55} y2={scaleY(p)} stroke="#1e222d" strokeWidth={0.5} />
          <text x={W - 53} y={scaleY(p) + 3} fill="#787b86" fontSize={7} fontFamily="monospace">{p.toFixed(4)}</text>
        </g>
      ))}

      {/* Volume bars */}
      {visible.map((c, i) => {
        const x = scaleX(i);
        const isGreen = c.c >= c.o;
        const vol = 5 + Math.random() * 20;
        return <rect key={`v${i}`} x={x} y={H - 15 - vol} width={cW} height={vol} fill={isGreen ? "#26a69a33" : "#ef535033"} />;
      })}

      {/* Candles with animation */}
      {visible.map((c, i) => {
        const x = scaleX(i);
        const isGreen = c.c >= c.o;
        const bodyTop = scaleY(Math.max(c.o, c.c));
        const bodyBot = scaleY(Math.min(c.o, c.c));
        const color = isGreen ? "#26a69a" : "#ef5350";
        const isNew = i === visibleCount - 1;
        return (
          <g key={i} style={isNew ? { animation: "fadeIn 0.3s ease-out" } : undefined}>
            <line x1={x + cW / 2} y1={scaleY(c.h)} x2={x + cW / 2} y2={bodyTop} stroke={color} strokeWidth={0.8} />
            <line x1={x + cW / 2} y1={bodyBot} x2={x + cW / 2} y2={scaleY(c.l)} stroke={color} strokeWidth={0.8} />
            <rect x={x} y={bodyTop} width={cW} height={Math.max(bodyBot - bodyTop, 0.5)} fill={color} />
          </g>
        );
      })}

      {/* Crosshair on last candle */}
      {visible.length > 0 && (() => {
        const last = visible[visible.length - 1];
        const lx = scaleX(visible.length - 1) + cW / 2;
        const ly = scaleY(last.c);
        return (
          <>
            <line x1={lx} y1={20} x2={lx} y2={H - 15} stroke="#787b8633" strokeWidth={0.5} strokeDasharray="3,3" />
            <line x1={pad} y1={ly} x2={W - 55} y2={ly} stroke="#787b8633" strokeWidth={0.5} strokeDasharray="3,3" />
            <rect x={W - 58} y={ly - 8} width={56} height={16} rx={2} fill={last.c >= last.o ? "#26a69a" : "#ef5350"} />
            <text x={W - 55} y={ly + 3} fill="white" fontSize={8} fontFamily="monospace">{last.c.toFixed(4)}</text>
          </>
        );
      })()}

      {/* Annotations */}
      {annotations.map((a, i) => {
        if (a.type === "zone" && a.price && a.price2) {
          return <rect key={i} x={pad} y={scaleY(a.price)} width={W - pad - 60}
            height={scaleY(a.price2) - scaleY(a.price)} fill={`${a.color || "#2962ff"}15`}
            stroke={`${a.color || "#2962ff"}44`} strokeDasharray="4,4"
            style={{ animation: "fadeIn 0.5s ease-out" }} />;
        }
        if (a.type === "label" && a.price && a.text) {
          return <text key={i} x={a.x || pad + 5} y={scaleY(a.price) - 5}
            fill={a.color || "#d1d4dc"} fontSize={9} fontWeight="bold" fontFamily="Inter, sans-serif"
            style={{ animation: "fadeIn 0.5s ease-out" }}>{a.text}</text>;
        }
        if (a.type === "circle" && a.price) {
          const cx = a.x || scaleX(visibleCount - 1) + cW / 2;
          return <circle key={i} cx={cx} cy={scaleY(a.price)} r={5}
            fill={a.color || "#ff9800"} style={{ animation: "pulse 1.5s infinite" }} />;
        }
        if (a.type === "arrow" && a.price && a.price2) {
          const x1 = a.x || pad + 30;
          const x2 = a.x2 || pad + 80;
          return <line key={i} x1={x1} y1={scaleY(a.price)} x2={x2} y2={scaleY(a.price2)}
            stroke={a.color || "#26a69a"} strokeWidth={2} markerEnd="url(#arrowG)"
            style={{ animation: "fadeIn 0.5s ease-out" }} />;
        }
        return null;
      })}

      {/* Arrow marker def */}
      <defs>
        <marker id="arrowG" markerWidth="8" markerHeight="6" refX="8" refY="3" orient="auto">
          <polygon points="0 0, 8 3, 0 6" fill="#26a69a" />
        </marker>
        <style>{`
          @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
          @keyframes pulse { 0%,100% { opacity: 0.6; } 50% { opacity: 1; } }
        `}</style>
      </defs>
    </svg>
  );
}

export default function VideoLesson({ title, steps, pair = "EUR/USD", timeframe = "H4" }: VideoLessonProps) {
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);
  const [candleCount, setCandleCount] = useState(0);
  const [progress, setProgress] = useState(0);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const speechRef = useRef<SpeechSynthesisUtterance | null>(null);

  const step = steps[currentStep];
  const totalDuration = steps.reduce((t, s) => t + s.duration, 0);

  const stopAll = useCallback(() => {
    if (timerRef.current) clearInterval(timerRef.current);
    if (typeof window !== "undefined" && window.speechSynthesis) window.speechSynthesis.cancel();
    setIsPlaying(false);
  }, []);

  const playStep = useCallback((stepIdx: number) => {
    if (stepIdx >= steps.length) { stopAll(); setProgress(100); return; }
    setCurrentStep(stepIdx);
    const s = steps[stepIdx];
    setCandleCount(0);

    // Animate candles appearing one by one
    let candleIdx = 0;
    const candleInterval = (s.duration * 1000) / (s.candles.length + 1);
    timerRef.current = setInterval(() => {
      candleIdx++;
      if (candleIdx <= s.candles.length) {
        setCandleCount(candleIdx);
      } else {
        if (timerRef.current) clearInterval(timerRef.current);
        // Next step after a small pause
        setTimeout(() => playStep(stepIdx + 1), 800);
      }
      // Update progress
      const elapsed = steps.slice(0, stepIdx).reduce((t, st) => t + st.duration, 0) + (candleIdx / s.candles.length) * s.duration;
      setProgress((elapsed / totalDuration) * 100);
    }, candleInterval);

    // TTS narration
    if (typeof window !== "undefined" && window.speechSynthesis) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(s.narration);
      const voices = window.speechSynthesis.getVoices();
      const esVoice = voices.find(v => v.lang.startsWith("es"));
      if (esVoice) utterance.voice = esVoice;
      utterance.lang = "es-ES";
      utterance.rate = 0.9;
      speechRef.current = utterance;
      window.speechSynthesis.speak(utterance);
    }
  }, [steps, totalDuration, stopAll]);

  const play = () => {
    setIsPlaying(true);
    playStep(0);
  };

  const stop = () => {
    stopAll();
    setCurrentStep(0);
    setCandleCount(0);
    setProgress(0);
  };

  useEffect(() => {
    return () => stopAll();
  }, [stopAll]);

  return (
    <div className="bg-[#0d0d15] border border-[#2a2a40] rounded-2xl overflow-hidden">
      {/* Header */}
      <div className="bg-[#1e222d] px-4 py-2 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-2 h-2 rounded-full bg-red-500" />
          <div className="w-2 h-2 rounded-full bg-yellow-500" />
          <div className="w-2 h-2 rounded-full bg-green-500" />
          <span className="text-[#d1d4dc] text-xs font-medium ml-2">{pair} · {timeframe}</span>
        </div>
        <span className="text-[#787b86] text-xs">Video-Leccion Interactiva</span>
      </div>

      {/* Chart area */}
      <div className="p-3">
        <AnimatedChart
          candles={step?.candles || []}
          visibleCount={candleCount}
          annotations={step?.annotations || []}
          W={700} H={320}
        />
      </div>

      {/* Narration text */}
      <div className="px-4 py-3 bg-[#131722] border-t border-[#1e222d] min-h-[60px]">
        <p className="text-[#d1d4dc] text-sm leading-relaxed">
          {step ? step.narration : title}
        </p>
      </div>

      {/* Controls */}
      <div className="px-4 py-3 bg-[#1e222d] flex items-center gap-4">
        {!isPlaying ? (
          <button onClick={play} className="bg-[#2962ff] hover:bg-[#1e53e5] text-white px-5 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition">
            <span>&#9654;</span> Reproducir
          </button>
        ) : (
          <button onClick={stop} className="bg-[#363a45] hover:bg-[#434651] text-[#d1d4dc] px-5 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition">
            <span>&#9632;</span> Detener
          </button>
        )}
        <div className="flex-1 h-1.5 bg-[#131722] rounded-full overflow-hidden">
          <div className="h-full bg-[#2962ff] rounded-full transition-all duration-300" style={{ width: `${progress}%` }} />
        </div>
        <span className="text-[#787b86] text-xs">Paso {currentStep + 1}/{steps.length}</span>
      </div>
    </div>
  );
}

// ============================================================================
// PRE-BUILT VIDEO LESSONS
// ============================================================================

export const VIDEO_LESSONS = {
  supportResistance: {
    title: "Soportes y Resistencias en Accion",
    pair: "EUR/USD",
    timeframe: "H4",
    steps: [
      {
        candles: [
          {o:1.0820,h:1.0835,l:1.0815,c:1.0830},{o:1.0830,h:1.0845,l:1.0825,c:1.0840},
          {o:1.0840,h:1.0855,l:1.0835,c:1.0850},{o:1.0850,h:1.0868,l:1.0845,c:1.0862},
          {o:1.0862,h:1.0878,l:1.0858,c:1.0875},{o:1.0875,h:1.0888,l:1.0870,c:1.0885},
        ],
        annotations: [],
        narration: "Observa como el precio va subiendo vela a vela. Estamos en una tendencia alcista en EUR/USD en temporalidad de 4 horas. Cada vela verde muestra dominio de los compradores.",
        duration: 6,
      },
      {
        candles: [
          {o:1.0820,h:1.0835,l:1.0815,c:1.0830},{o:1.0830,h:1.0845,l:1.0825,c:1.0840},
          {o:1.0840,h:1.0855,l:1.0835,c:1.0850},{o:1.0850,h:1.0868,l:1.0845,c:1.0862},
          {o:1.0862,h:1.0878,l:1.0858,c:1.0875},{o:1.0875,h:1.0888,l:1.0870,c:1.0885},
          {o:1.0885,h:1.0895,l:1.0878,c:1.0882},{o:1.0882,h:1.0890,l:1.0870,c:1.0875},
          {o:1.0875,h:1.0882,l:1.0862,c:1.0865},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0895, price2: 1.0882, color: "#ef5350" },
          { type: "label" as const, price: 1.0898, text: "RESISTENCIA", color: "#ef5350" },
        ],
        narration: "Aqui vemos como el precio llega a la zona de 1.0890 y es RECHAZADO. Las velas empiezan a tener mechas superiores y luego aparecen velas rojas. Esta zona se convierte en RESISTENCIA. El precio no puede superarla.",
        duration: 7,
      },
      {
        candles: [
          {o:1.0820,h:1.0835,l:1.0815,c:1.0830},{o:1.0830,h:1.0845,l:1.0825,c:1.0840},
          {o:1.0840,h:1.0855,l:1.0835,c:1.0850},{o:1.0850,h:1.0868,l:1.0845,c:1.0862},
          {o:1.0862,h:1.0878,l:1.0858,c:1.0875},{o:1.0875,h:1.0888,l:1.0870,c:1.0885},
          {o:1.0885,h:1.0895,l:1.0878,c:1.0882},{o:1.0882,h:1.0890,l:1.0870,c:1.0875},
          {o:1.0875,h:1.0882,l:1.0862,c:1.0865},{o:1.0865,h:1.0870,l:1.0848,c:1.0852},
          {o:1.0852,h:1.0860,l:1.0838,c:1.0842},{o:1.0842,h:1.0855,l:1.0835,c:1.0850},
          {o:1.0850,h:1.0865,l:1.0845,c:1.0862},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0895, price2: 1.0882, color: "#ef5350" },
          { type: "label" as const, price: 1.0898, text: "RESISTENCIA", color: "#ef5350" },
          { type: "zone" as const, price: 1.0850, price2: 1.0835, color: "#26a69a" },
          { type: "label" as const, price: 1.0832, text: "SOPORTE", color: "#26a69a", x: 15 },
          { type: "circle" as const, price: 1.0842, color: "#26a69a", x: 175 },
        ],
        narration: "El precio cae hasta la zona de 1.0835 a 1.0850 y aqui REBOTA. Esta es la zona de SOPORTE. Los compradores defienden este nivel. Fijate en la vela con mecha inferior larga: es un martillo, senal de rechazo. El precio rebota hacia arriba desde el soporte.",
        duration: 8,
      },
      {
        candles: [
          {o:1.0820,h:1.0835,l:1.0815,c:1.0830},{o:1.0830,h:1.0845,l:1.0825,c:1.0840},
          {o:1.0840,h:1.0855,l:1.0835,c:1.0850},{o:1.0850,h:1.0868,l:1.0845,c:1.0862},
          {o:1.0862,h:1.0878,l:1.0858,c:1.0875},{o:1.0875,h:1.0888,l:1.0870,c:1.0885},
          {o:1.0885,h:1.0895,l:1.0878,c:1.0882},{o:1.0882,h:1.0890,l:1.0870,c:1.0875},
          {o:1.0875,h:1.0882,l:1.0862,c:1.0865},{o:1.0865,h:1.0870,l:1.0848,c:1.0852},
          {o:1.0852,h:1.0860,l:1.0838,c:1.0842},{o:1.0842,h:1.0855,l:1.0835,c:1.0850},
          {o:1.0850,h:1.0865,l:1.0845,c:1.0862},{o:1.0862,h:1.0878,l:1.0858,c:1.0875},
          {o:1.0875,h:1.0892,l:1.0872,c:1.0890},{o:1.0890,h:1.0910,l:1.0888,c:1.0908},
          {o:1.0908,h:1.0925,l:1.0905,c:1.0922},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0895, price2: 1.0882, color: "#26a69a" },
          { type: "label" as const, price: 1.0880, text: "RESISTENCIA → SOPORTE (cambio polaridad)", color: "#ff9800", x: 15 },
          { type: "zone" as const, price: 1.0850, price2: 1.0835, color: "#26a69a" },
          { type: "label" as const, price: 1.0832, text: "SOPORTE", color: "#26a69a", x: 15 },
          { type: "circle" as const, price: 1.0892, color: "#ff9800", x: 240 },
        ],
        narration: "Y aqui viene lo mas importante: el precio vuelve a subir y esta vez ROMPE la resistencia con fuerza. Cuando una resistencia se rompe, se convierte en SOPORTE. Esto se llama CAMBIO DE POLARIDAD. Ahora la zona de 1.0885 a 1.0895 que antes frenaba la subida, ahora la sostiene. Este concepto es fundamental en todo el trading.",
        duration: 10,
      },
    ],
  },
  orderBlockTrade: {
    title: "Operacion con Order Block (Setup Completo)",
    pair: "EUR/USD",
    timeframe: "H1",
    steps: [
      {
        candles: [
          {o:1.0880,h:1.0888,l:1.0872,c:1.0878},{o:1.0878,h:1.0885,l:1.0868,c:1.0872},
          {o:1.0872,h:1.0878,l:1.0862,c:1.0865},{o:1.0865,h:1.0872,l:1.0855,c:1.0858},
          {o:1.0858,h:1.0865,l:1.0848,c:1.0852},
        ],
        annotations: [],
        narration: "Estamos observando EUR/USD en temporalidad de 1 hora. El precio esta cayendo, formando una tendencia bajista a corto plazo. Vemos velas rojas consecutivas. Los vendedores dominan.",
        duration: 5,
      },
      {
        candles: [
          {o:1.0880,h:1.0888,l:1.0872,c:1.0878},{o:1.0878,h:1.0885,l:1.0868,c:1.0872},
          {o:1.0872,h:1.0878,l:1.0862,c:1.0865},{o:1.0865,h:1.0872,l:1.0855,c:1.0858},
          {o:1.0858,h:1.0865,l:1.0848,c:1.0852},
          // OB candle
          {o:1.0852,h:1.0858,l:1.0838,c:1.0840},
          // Displacement
          {o:1.0842,h:1.0875,l:1.0840,c:1.0872},{o:1.0872,h:1.0900,l:1.0870,c:1.0898},
          {o:1.0898,h:1.0922,l:1.0895,c:1.0920},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0858, price2: 1.0838, color: "#2962ff" },
          { type: "label" as const, price: 1.0835, text: "ORDER BLOCK (ultima roja antes del movimiento)", color: "#2962ff", x: 15 },
        ],
        narration: "Atencion! Mira esta vela roja grande. Es la ULTIMA vela bajista antes de un movimiento alcista explosivo. Esto es un ORDER BLOCK. Las instituciones acumularon posiciones de compra aqui. Las 3 velas verdes grandes que siguen son el DISPLACEMENT: movimiento agresivo que confirma la intencion real del mercado.",
        duration: 8,
      },
      {
        candles: [
          {o:1.0880,h:1.0888,l:1.0872,c:1.0878},{o:1.0878,h:1.0885,l:1.0868,c:1.0872},
          {o:1.0872,h:1.0878,l:1.0862,c:1.0865},{o:1.0865,h:1.0872,l:1.0855,c:1.0858},
          {o:1.0858,h:1.0865,l:1.0848,c:1.0852},{o:1.0852,h:1.0858,l:1.0838,c:1.0840},
          {o:1.0842,h:1.0875,l:1.0840,c:1.0872},{o:1.0872,h:1.0900,l:1.0870,c:1.0898},
          {o:1.0898,h:1.0922,l:1.0895,c:1.0920},
          // Pullback
          {o:1.0920,h:1.0925,l:1.0905,c:1.0908},{o:1.0908,h:1.0912,l:1.0892,c:1.0895},
          {o:1.0895,h:1.0900,l:1.0878,c:1.0882},{o:1.0882,h:1.0888,l:1.0845,c:1.0848},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0858, price2: 1.0838, color: "#2962ff" },
          { type: "label" as const, price: 1.0835, text: "ORDER BLOCK", color: "#2962ff", x: 15 },
          { type: "circle" as const, price: 1.0848, color: "#26a69a", x: 210 },
          { type: "label" as const, price: 1.0860, text: "Precio retorna al OB → ENTRADA LONG", color: "#26a69a", x: 220 },
        ],
        narration: "Ahora el precio retrocede. Baja vela a vela hasta llegar exactamente a la zona del Order Block. Mira como la ultima vela tiene una mecha inferior que toca el OB y luego cierra con rechazo. ESTE es el momento de entrar en LONG. Stop Loss debajo del Order Block, Take Profit en el maximo anterior o mas alla.",
        duration: 8,
      },
      {
        candles: [
          {o:1.0880,h:1.0888,l:1.0872,c:1.0878},{o:1.0878,h:1.0885,l:1.0868,c:1.0872},
          {o:1.0872,h:1.0878,l:1.0862,c:1.0865},{o:1.0865,h:1.0872,l:1.0855,c:1.0858},
          {o:1.0858,h:1.0865,l:1.0848,c:1.0852},{o:1.0852,h:1.0858,l:1.0838,c:1.0840},
          {o:1.0842,h:1.0875,l:1.0840,c:1.0872},{o:1.0872,h:1.0900,l:1.0870,c:1.0898},
          {o:1.0898,h:1.0922,l:1.0895,c:1.0920},{o:1.0920,h:1.0925,l:1.0905,c:1.0908},
          {o:1.0908,h:1.0912,l:1.0892,c:1.0895},{o:1.0895,h:1.0900,l:1.0878,c:1.0882},
          {o:1.0882,h:1.0888,l:1.0845,c:1.0848},
          // Rally from OB
          {o:1.0848,h:1.0878,l:1.0845,c:1.0875},{o:1.0875,h:1.0905,l:1.0872,c:1.0902},
          {o:1.0902,h:1.0928,l:1.0900,c:1.0925},{o:1.0925,h:1.0948,l:1.0922,c:1.0945},
        ],
        annotations: [
          { type: "zone" as const, price: 1.0858, price2: 1.0838, color: "#2962ff" },
          { type: "label" as const, price: 1.0948, text: "TP alcanzado: +100 pips", color: "#26a69a", x: 250 },
          { type: "label" as const, price: 1.0835, text: "SL: -15 pips | R:R = 1:6.7", color: "#ef5350", x: 15 },
        ],
        narration: "Y aqui tienes el resultado. El precio reboto perfectamente desde el Order Block y subio con fuerza. Si entraste en la zona del OB con un Stop Loss de 15 pips y el precio subio 100 pips, tu ratio riesgo beneficio fue de 1 a 6.7. Excelente. Este es el poder de operar con Smart Money Concepts: entradas precisas con ratios de riesgo beneficio muy favorables.",
        duration: 9,
      },
    ],
  },
};
